### ISSUE TITLE
公開終了日時に過去の日時を設定できる

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#104]
MTではエラーを表示しますが、アプリではどうしますか？

Steps:
1. 記事の作成
2. 設定画面で、終了日時を設定
3. 過去の日時を入力して、完了
4. MTに送信

Expected: （エラーを表示？）
Observed: そのまま保存／送信できる。MTで編集画面を開くと、「公開終了日は、未来の日時を指定してください。」とエラーが表示される

**Comment by cheebow** [comment]
修正しました

**Comment by cmatsuo** [comment]
verified fix.
