### ISSUE TITLE
カメラにアクセスできないときの画面 アイコンと文字色の変更

### ISSUE THREAD

**Issue by oguraayumi** [movabletype/smartphone-app#110]
![toph](https://cloud.githubusercontent.com/assets/618638/8492153/b49a06ae-2180-11e5-90c0-74bdda4ee412.jpg)

カメラにアクセスできないときの画面でアイコンと文字色を
変更することはできますか？
できるようでしたら、お願いしたいです。

ガイドと仕様書（最新版にもいれています。）
https://drive.google.com/a/sixapart.com/folderview?id=0B3DAAwwej82XfjFCcV9BZ19KalZKcHpVYzZyU1FIQ2h0c3lxbHJmaEpxUnExT3o3emdsUTQ&usp=sharing

**Comment by cheebow** [comment]
対応しました

**Comment by cmatsuo** [comment]
verified fix.
