### ISSUE TITLE
ページ：画像の利用状況に関する表示（MTにすでに保存されているページを編集、画像の挿入を行った場合）

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#112]
Steps:
1. ウェブページを作成
2. MTに送信（MT側でウェブページを作成してもOK）
3. ウェブページの一覧から、1-2で作成したページを選択し、編集画面を開く
4. 本文、または追記の編集画面を開く
5. プレーンテキストの編集画面で、カメラアイコンをクリックし、画像を挿入
6. MTに送信
7. MTで、5で編集したページの編集画面を開く

Expected: 画面右下の「ウェブページアイテム」ウィジェットにも挿入した画像が表示されている。また、画像の編集画面にも、利用状況ウィジェットに記事へのリンクが表示されている。
Observed: 「ウェブページアイテム」ウィジェットに、挿入した画像が表示されない。（画像編集画面側はきちんと表示されている）

記事の編集の場合この現象は起こりません。　#67 の修正漏れかもしれません。

**Comment by yuji** [comment]
This issue will be fixed with Data API side.

**Comment by ikoaoki** [comment]
https://movabletype.fogbugz.com/f/cases/113213/
上記case、以下のように確認してcloseしていること報告いたします。

こちら、MTiOSアプリより、最新のMTクラウド環境6.2.1602へ、ページを送信するテストを行い、報告されている現象が解消されていることを、確認いたしました。
また、合わせてアプリを以下環境でテストしましたが、問題ありませんでした。
・iOS 8
・i0S 9.0
・iOS 9.1
・iOS 9.2
