### ISSUE TITLE
Add ability to upload multiple photos at a time

### ISSUE THREAD

**Issue by yuji** [movabletype/smartphone-app#116]
Add ability to upload multiple photos at a time

**Comment by cheebow** [comment]
@yuji これは、写真を写真を複数枚設定してAssetとして登録するということですが、iOSの標準UIでは写真を複数選択することができないので、別途複数選択用のUIを検討する必要があります。

**Comment by yuji** [comment]
@cheebow 写真アプリみたいなのはUIxxには無いのですか・・・
2/1の検討事項にしましょうか

**Comment by yuji** [comment]
@cheebow OSS ライブラリから見繕う

**Comment by yuji** [comment]
複数選択 -> 対象リストを表示 -> 1つずつアップ -> 失敗したらそこから

**Comment by cheebow** [comment]
これが良さげですね

https://github.com/questbeat/QBImagePicker

**Comment by cheebow** [comment]
@yuji 
写真を複数選んでAssetにできる機能なんですけど、選択できる画像の数の最大数を決められるんですけど、どうしましょう？　無制限は厳しいですよね。

**Comment by cheebow** [comment]
とりあえず、8枚にします。

**Comment by cheebow** [comment]
実装しました

**Comment by cheebow** [comment]
プログレス画面を修正します

**Comment by cheebow** [comment]
実装できました

**Comment by yuji** [comment]
@cheebow 8枚了解です。連続で選んだとして2列分ってことですね。

**Comment by yuji** [comment]
@cmatsuo build76. spec is here: https://github.com/movabletype/smartphone-app/wiki/v1_1_0#multiple-upload-116

**Comment by cmatsuo** [comment]
Verified implements.
