### ISSUE TITLE
iOS 9 Beta: サインインすると Unauthorized というエラーが発生する

### ISSUE THREAD

**Issue by dreamagicjp** [movabletype/smartphone-app#118]
iOS 9 Beta でサインインすると Unauthorized というエラーが発生し、サインインに失敗する現象が発生します。

![img_8106](https://cloud.githubusercontent.com/assets/207862/8959469/fdb21a46-3645-11e5-93a9-e5a76f61b49c.PNG)

**Comment by dreamagicjp** [comment]
@yuji (Maybe) this issue is still reproducible with iOS 9 beta 5 on iPhone 6. We probably should start try to fix this.

**Comment by yuji** [comment]
Fixed to work with iOS9 by a build 1.0.1.60
