### ISSUE TITLE
Disable autocorrect for the login page fields

### ISSUE THREAD

**Issue by padawan** [movabletype/smartphone-app#119]
On the login page, the iOS autocorrector remains enabled for all fields. This makes entering the URL very difficult as one has to refuse the proposed corrections for things like domain names or "cgi-bin" or even "mt" (and the habit of iOS to add a trailing space each time one dismisses its corrections).

Please disable auto-correct for all fields on the login page.

(Tested on iOS 8.4 (12H143) on a iPhone.)

**Comment by yuji** [comment]
Thanks!

**Comment by yuji** [comment]
Fixed in development.
