### ISSUE TITLE
Add EMEA translation

### ISSUE THREAD

**Issue by yuji** [movabletype/smartphone-app#121]

**Comment by yuji** [comment]
Maarten and his team is now working on.

**Comment by yuji** [comment]
Already done!

**Comment by yuji** [comment]
設定から言語を変えて変わることを確認。ってとこですかね。

**Comment by cmatsuo** [comment]
言語設定変更で、ドイツ語、スペイン語、オランダ語、フランス語での表示ができることを確認。
