### ISSUE TITLE
画像のアップロード先に日本語や絵文字など、non-ascii文字が入力できてしまう

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#122]
Steps:
1. サイト／ブログダッシュボード＞設定（サイト名横のアイコンをクリック）＞アップロード先
2. 「てすと」と入力後、完了をクリック

Expected: 「有効なパス名を指定してください。」等のエラーを表示
Observed: 保存を完了して設定画面に戻る

**Comment by yuji** [comment]
絵文字のチェックってできますかね

**Comment by cheebow** [comment]
@yuji 
絵文字チェックは
http://d.hatena.ne.jp/kurusaki/20100425/1272187639
こんな感じで出来そうです。
日本語も弾くのであれば、URLとして有効な文字かどうかをチェックしたほうがよさそう。

**Comment by yuji** [comment]
@cheebow 管理画面上では日本語弾いているので URL チェックにしましょう

**Comment by cheebow** [comment]
@yuji 管理画面でどういう正規表現を使っているか教えてください

**Comment by yuji** [comment]
@cheebow: JSの正規表現ですが

    // RegExp code taken from http://bassistance.de/jquery-plugins/jquery-plugin-validation/                      
    '.url': function ($e) {                                                                                       
        return !$e.val() || /^(https?|ftp):\/\/(((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\
%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:)*@)?(((\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\\
.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5]))|((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDC\
F\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uF\
DCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\\
uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\u\
FDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?)(:\d*)?)(\/((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7\
FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)+(\/(([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\
\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)*)*)?)?(\?((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\u\
FDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|[\uE000-\uF8FF]|\/|\?)*)?(\#((([a-z]|\d|-|\.|_|~|[\u00A\
0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|\/|\?)*)?$/i.test($e.val());           
    },

**Comment by cheebow** [comment]
@yuji これ、パスのチェックではなくてURLのチェックですよね？

**Comment by yuji** [comment]
@cheebow あ。

path.match(/^[^\s<>\#%"\,\{\}\\|\\\^\[\]`]*$/);

こちらでした。すっきり。

**Comment by cheebow** [comment]
修正しました

**Comment by cmatsuo** [comment]
@cheebow @yuji 
URLに含められない文字などのバリデーションもするようにすることは可能でしょうか？

以下の一覧の、使用可能な文字、使用可能な記号（* を除く）以外を全て利用できない状態が望ましいです。
http://www.ipentec.com/document/document.aspx?page=web-url-invalid-char

**Comment by cheebow** [comment]
@yuji MTの管理画面も統一したほうが良いですよね？これも、MTGの課題にしましょう

**Comment by cmatsuo** [comment]
MT側での同様の問題について、fbzにケース作成しました　
https://movabletype.fogbugz.com/f/cases/113758/Upload-Destination-path-validation

**Comment by yuji** [comment]
@cmatsuo とりあえず、^[^\s<>#%"\,{}\|\^[]`]*$ これらがエラーになるところは検証できてれば一旦閉じますか。MTの件と合わせて別件にしましょう。

**Comment by yuji** [comment]
正規表現ブロック抜き忘れてる

<>#%"\,{}|[]`

これ

**Comment by cmatsuo** [comment]
@yuji 
#だけエラー。残り（<>%"\,{}|[]`）は問題なく保存できます。

**Comment by yuji** [comment]
@cheebow # はディレクトリ名としてはセーフなんですけど、URL としては NG になるので入れられないようにしたほうが得策かも。

**Comment by cmatsuo** [comment]
@yuji いや、逆。現状、#はエラーになるので入れられない、それ以外は全部入れられる状態。

**Comment by yuji** [comment]
おっと。
@cheebow 正規表現の判定結果が逆ですかねもしかすると

**Comment by cheebow** [comment]
@yuji @cmatsuo 
CMSと動作が同じであれば問題ないと思うのですが、僕は何をしたら良いですか？

**Comment by yuji** [comment]
@cmatsuo @cheebow よくよく整理すると MT 側で # が入るのがいくない。って気がしてきた・・・。
こちら、とくにこれ以上の対応は今のところ無しでOKですね。

**Comment by yuji** [comment]
@cheebow 再度整理しました。把握しました。

# がエラー ... これはOK
\ " ' | * ` ^ > < ) ( } { ] [ がエラーにならない ... MT側でもなっていない。ということらしい。

ということで、日本語と絵文字のチェックだけとりあえず入れておいていただければと。

**Comment by cheebow** [comment]
@yuji 今、日本語と絵文字はエラーで弾いていると思うんですが、まだ足りないものがありますか？

**Comment by yuji** [comment]
@cheebow それであれば問題なしです！
@cmatsuo # が入らないのは むしろ好ましいのでアプリ側はこのままにしておいて、残りはMT側の修正と将来合わせる感じで別ケースかするってのでどうでしょ

**Comment by cmatsuo** [comment]
日本語、絵文字が入力できないことを確認。
MT側のvalidation機能更新時に、#223 で確認します。
