### ISSUE TITLE
Helpのリンク先が、日本で設定してあっても、ja（日本語）にならない

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#123]
システム＞設定＞ヘルプ
以下のリンク先になるようにお願いします。

ja: http://www.movabletype.jp/documentation/mtios/help
ja以外: http://www.movabletype.jp/documentation/mtios/help/en

![image](https://cloud.githubusercontent.com/assets/546386/10451168/884664ae-71d9-11e5-8a1f-f41451a72d20.png)

**Comment by cmatsuo** [comment]
Note to self: iOS8と9の両方で修正を確認のこと。

**Comment by yuji** [comment]
done!

**Comment by cmatsuo** [comment]
verified fix!
