### ISSUE TITLE
Basic認証がかからない

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#124]
mt6qa3で作業しています。
クラウドサービスの機能で設定した管理画面、ウェブサイト／ブログへのBasic認証が無視されます。

**Comment by yuji** [comment]
管理画面へのbasic認証は、クラウド相当では掛からない仕様だったので。いまは、mt6qa3に限りCMSへのbasic認証がdata_apiにもかかるようにしました。

**Comment by cmatsuo** [comment]
Thanks, verified with mt6qa3. And split Basic Auth behavior for website/blog. #129
