### ISSUE TITLE
L10N: Do not have permission to retrive the requested fields.

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#126]
サイトに権限を持っていない（子ブログに権限を持っている）ユーザーが、サイトのユーザーダッシュボードにアクセスした際のポップアップ

![image](https://cloud.githubusercontent.com/assets/546386/10473296/dca4c672-7264-11e5-9b4a-cbb0d7f63359.png)

**Comment by yuji** [comment]
oh... this message was outputs by Data API... File a new case in FogBugz.

https://movabletype.fogbugz.com/f/cases/113510/L10N-Do-not-have-permission-to-retrive-the-requested-fields
