### ISSUE TITLE
Category/Folder setting screen down app

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#128]
Steps:
1. Go to MT on PC.
2. Create some categories for a website/blog.
3. Go to Create a new Entry on app.
4. Tap Category.

Expected: Go to category setting screen.
Observed: MTiOS down.

FYI: It's same about folder for Create/Edit Page.

**Comment by yuji** [comment]
hmm... still happened sometimes...

**Comment by yuji** [comment]
Maybe fixed.

**Comment by cmatsuo** [comment]
verified fix.
