### ISSUE TITLE
アイテムにサイズ0×0の画像が出来て削除出来ない。

### ISSUE THREAD

**Issue by ikoaoki** [movabletype/smartphone-app#130]
発生タイミング、再現手順は確定出来ていないのですが、
「アイテムの一覧」を読み込みに行く時に、時折落ちるので、そこで発生した印象です。

### 現象
アイテムに「サイズ0×0」の画像が出来て削除出来ない。
上記画像があると、他アイテム一覧が取得できなくなり、「アイテムを取得しています…」の画面で止まってしまう。

### 発生したと思われる状況
1) アイテムを取得する為に、リフレッシュを行う。
2) アイテムが取得できないまま、アプリが落ちる

3) 再度サインインして、ブログ＞アイテム　に行く。
4) アイテム欄に、サイズ0×0 の画像ができている。
　→この画像を削除しようとすると、Unknown Endpoint と出て削除できない。

5) アイテム一覧をリフレッシュを行う。
6) 他アイテムもあるはずだが、「アイテムを取得しています…」の画面のまま、一向に進まなくなる。

### メモ
ログアウト、ログイン、を繰り返しても、サイズ0×0 の画像　は消えておらず、いつまでたっても、アイテム一覧の取得ができない…。

iPhone側の「写真」にも、
CMS側にも、サイズ0×0 の画像は無い。

この画像が発生してから、サイト＆ブログ一覧の取得にも度々失敗するようになった。

アプリを再インストールなどすると、サイズ0×0 の画像はなくなり、問題なくアイテム一覧が再度取得出来るようになりました。

![image1](https://cloud.githubusercontent.com/assets/6724607/10475485/177120ec-727f-11e5-94cb-2304864d59e4.PNG)
![image2](https://cloud.githubusercontent.com/assets/6724607/10475486/179f8a9a-727f-11e5-9591-8a1d957843c2.PNG)

**Comment by yuji** [comment]
Maybe communication error with DataAPI. Set milestone

**Comment by ikoaoki** [comment]
10/20 memo
バージョン63にしてから、10/20中、この現象は発生していない。

**Comment by yuji** [comment]
これも再現しないな・・・うーむ

**Comment by cmatsuo** [comment]
@yuji iOS9(5s)では、アイテムの一覧で落ちるという動作自体がこれまでのところ起きてません。端末やOSに固有の可能性あるかも。

**Comment by yuji** [comment]
一旦クローズ。また起きたら新しく起こす
