### ISSUE TITLE
Create/Edit screen sorting setting should effect per user and site/blog.

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#133]
Steps:
0. You have 2 member at least for the website/blog who have create entry permission.
1. Sign in as user_A.
2. Go to Create Entry > Sorting (Click "Edit" on footer).
3. Sort and hide some fields, and save it.
4. Make sure the sorting setting was saved for user_A.
5. Sign out, and sign in as user_B this time.
6. Go to Create Entry.

Expected: Sorting setting doesn't effect for user_B.
Observed: Find the same setting user_A did at step 3. 

Spec says, "入れ替えられた順番・表示非表示の設定は、アカウント毎・サイト単位でアプリケーション内部に保持される。".

**Comment by yuji** [comment]
Does not implemented yet? omg. set milestone to 1.1

**Comment by cheebow** [comment]
@yuji これ、仕様を見落としていました。
ソート順のほかに、エントリやページのローカル保存もユーザ別になっていません。
これを修正すると、以前のデータが読み込めなくなってしまうのですが、どう対応しましょう。

**Comment by yuji** [comment]
1台のスマホをみんなで使うユースケースは、有っても非常にレアだと思っているので保存された保存されたソート順やローカル保存を開いた段階で、ユーザーに紐付いてなければそのユーザーにひも付けけして更新しちゃう。とかできますかね？

**Comment by cheebow** [comment]
@yuji ユーザごとに保存ディレクトリを変えようかと思っていたので、そうするとそもそも開くことができないんですよね。ちょっと考えてみます。
起動時に全データをなめて修正するとか大掛かりなことになるかも

**Comment by cheebow** [comment]
起動時に古いデータを移動するようにしました

**Comment by cmatsuo** [comment]
verified fix.
エントリやページのローカル保存に関しては、 #97 があったので、そちらもクローズ。
