### ISSUE TITLE
Date picker is left aligned in iPhone 6/6 plus

### ISSUE THREAD

**Issue by takkyun** [movabletype/smartphone-app#135]
As per attached screenshot, date picker in date selection view is left aligned on iPhone 6/6 Plus.  It should be have same width as screen or centre aligned.

It seems misconfiguration in its storyboard (`DatePicker.storyboard`).  I am not familiar with setting up layout constraint on interface builder (I'm usually setting them up programatically), so I am not too sure what's best approach to fix.

![simulator_screen_shot_14_10_2015_22_21_57](https://cloud.githubusercontent.com/assets/1464708/10479911/892f9864-72c3-11e5-99de-3212e01d05a4.png)

===

添付画像の通り、iPhone 6/6 Plus にて日付設定画面のデータピッカーの右側に余白があります。
画面と同じ幅もしくは、画面中央に表示するのが自然だと思います。

`DatePicker.storyboard`での Autolayout の Constraint が正しく設定されていないようです。

**Comment by yuji** [comment]
Thank you for your report!

**Comment by yuji** [comment]
Hi takkyun, Thanks for your pull request. I merged your changes but some commits were ignored because these are unnecessary, I think. Thanks again.

**Comment by cmatsuo** [comment]
verified fix.
