### ISSUE TITLE
Embed and multiline text custom fields don't need Rich text Editor

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#136]
As well as single line text custom field. Or, do they?

![image](https://cloud.githubusercontent.com/assets/546386/10502870/70b4e5c4-732b-11e5-9a09-4085dbbc912e.png)

**Comment by cheebow** [comment]
HTMLエディタを表示するようにしました

**Comment by yuji** [comment]
At Build 68

**Comment by cmatsuo** [comment]
@yuji 
They're still has picture upload feature. Do we need this for Embed and multiline text CFs?

![img_0101](https://cloud.githubusercontent.com/assets/546386/12541870/7f9e1afe-c35f-11e5-823e-49f7c644293d.jpg)

**Comment by yuji** [comment]
@cheebow: Can hidden camera icon?

**Comment by cmatsuo** [comment]
@yuji @cheebow I think it's better if it could be as same as, for example, single line text CF's edit screen.

**Comment by yuji** [comment]
@cmatsuo agreed. 

@cheebow Can we hid camera icon and wysiwyg editor on all of CF's field?

**Comment by cheebow** [comment]
@yuji wysiwygエディタではなくてHTMLエディタですよね？で、カメラボタンだけ取るという。

**Comment by yuji** [comment]
@cheebow CFの入力は単行入力でもHTMLエディタでカメラなしでお願いします〜
アイテムのところくらいですね。カメラ。

**Comment by cheebow** [comment]
@yuji 単行はHTMLエディタじゃないほうが良いですよね？改行できてしまうので。
埋め込み、テキストエリアだけがHTMLエディタですよね。

**Comment by cheebow** [comment]
@yuji 　埋め込み、テキストエリアだけをカメラボタンなしHTMLエディタを表示するようにしました。
単行テキストは今まで通り普通のテキストエディタを表示しています。

**Comment by yuji** [comment]
> 単行テキストは今まで通り普通のテキストエディタを表示しています。
それでOKです！

**Comment by cmatsuo** [comment]
verified fix.
