### ISSUE TITLE
Need to mark required CF on MTiOS

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#137]
App says you need to put into required field for save, but you can't see which one is the required on the screen.
On CMS, required CF marked by asterisk.

![image](https://cloud.githubusercontent.com/assets/546386/10503473/49f51bce-7331-11e5-9c08-b641b11fc956.png)

**Comment by yuji** [comment]
必須である。というのがわかるにはどうするか。UIの点から一度お願いしますー

**Comment by yuji** [comment]
#138 から転載（間違えた）

![portrait - webpage](https://cloud.githubusercontent.com/assets/618638/12473471/a53d5840-c055-11e5-8ea1-30a682608d00.png)
項目を、必須とoptionalのエリアに分けるとかはどうでしょうか。

または、必須の中にoptional項目が含まれる場合を考えて
必須部分を入力している最中にそのブロックのoptional項目を展開して出すとか…

@yuji

**Comment by yuji** [comment]
required と optional で並びを分けてしまうと困るユーザーもいるのではないか、というかんじもしますが、どうですかねー？

**Comment by yuji** [comment]
@oguraayumi 本文、タイトルとかが枠組みの外にあるのでハテ？と思わないでもないかも。悩ましい・・・。先頭に * がやっぱり無難なんかなあ・・・
もう一発、アイディア出せますかね？

**Comment by oguraayumi** [comment]
![portrait - webpage](https://cloud.githubusercontent.com/assets/618638/12781351/2ed9c2e4-cab7-11e5-928a-ca124f17ba69.png)
オプショナルの項目を一段下の階層に入れるのはどうでしょうか。
@yuji

**Comment by yuji** [comment]
@oguraayumi この場合って、

Optional > 
　　オプショナルな項目名 >
　　　　入力欄

てきな移動って感じです？

**Comment by cheebow** [comment]
@yuji @oguraayumi 
この画面の項目ってユーザが自由に並び替えられるので、これだとまずい気がします。

**Comment by yuji** [comment]
@cheebow @oguraayumi たしかに。アプリ側からは順番に意味を持たせないほうがいいですね。CFで追加された項目自体は、エンドユーザーからするとCFかどうかも意識してないレベルである可能性が高いので、Required / Optional 方式も取りにくくもあるので、やっぱり悩ましい・・・。

**Comment by oguraayumi** [comment]
![portrait - webpage](https://cloud.githubusercontent.com/assets/618638/12871221/5ceea296-cdb2-11e5-955e-3071fe69dc07.png)
![portrait - webpage2](https://cloud.githubusercontent.com/assets/618638/12871220/5ced6804-cdb2-11e5-85fd-34d57dc32e94.png)
>並べ替え
そうですね ><
他アプリを参考にまた作ってみました。ベタになってしまったのですが2種類シンプルなものを作成しました。
@yuji @cheebow

**Comment by yuji** [comment]
@cheebow @oguraayumi 右に赤アスタリスク。ですかねえ・・・。モバイルだと領域も狭いしかえって合理的なのかもですねえ。

**Comment by cheebow** [comment]
@yuji @oguraayumi 文字自体を赤くしてボールドにするってのはどうですかね？

**Comment by yuji** [comment]
@oguraayumi 赤文字ボールド、試して見れますか？

＃アクセシビリティ的には色はアレですけど、ボールドにしているから違いを出せている。ということになるかしらね。

**Comment by oguraayumi** [comment]
![portrait - webpage2](https://cloud.githubusercontent.com/assets/618638/12937257/3048e492-cfea-11e5-88f0-0d818df2b6af.png)
![portrait - webpage3](https://cloud.githubusercontent.com/assets/618638/12937258/304965fc-cfea-11e5-8655-f87f65486ac2.png)
赤文字と黒文字でboldにしたものをつくってみました。
@yuji @cheebow

**Comment by yuji** [comment]
必須かどうかの判別はこれでつくかな。

@cheebow どすかね？

**Comment by cmatsuo** [comment]
うーむ。なんとなくやりすぎ感あるそうな。アスタリスクは偉大なのかもしれない気がしてきた。
上のほうで、 @oguraayumi さんがアップしてる、前赤ポチをアスタリスクにしてみたら…どんな印象になるんですかね？やはり、やりすぎなかんじになるんでしょうか？

**Comment by oguraayumi** [comment]
![portrait - webpage4](https://cloud.githubusercontent.com/assets/618638/12938242/4efa8e36-cff4-11e5-8391-52139bf0b585.png)
@cmatsuo @yuji @cheebow 
こんなかんじです。大きさは変えられます。

**Comment by cmatsuo** [comment]
アスタリスクが分かりやすいような気がします。サイズはこれで良いのでは。（もしかして、黒でもいいくらいかも）

**Comment by yuji** [comment]
@cmatsuo @cheebow @oguraayumi 巡り巡って、やっぱりこれが妥当なのかもしれない。

**Comment by cheebow** [comment]
@yuji これでいきましょうか。OKなら画像を用意していただけると！

**Comment by yuji** [comment]
@cheebow @oguraayumi んだばこれでいきましょ

**Comment by oguraayumi** [comment]
アスタリスクの画像こちらにupしました
https://drive.google.com/open?id=0B3DAAwwej82XeU1ldUNlT2xmY28
zeplin
一番上の必須マークがスライス切ってあります。
https://app.zeplin.io/project.html#pid=56a70f84c53ee8e71c6043f7&sid=56baf3f26498ba9d0beb06aa
@cheebow

**Comment by cheebow** [comment]
実装しました。
項目の並べ替え画面でも＊を表示するようにしてみました。

**Comment by yuji** [comment]
@cmatsuo build 77

**Comment by cmatsuo** [comment]
実装確認しました。いいですね。
