### ISSUE TITLE
Loophole for required CF

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#138]
Steps:
1. Create a required text CF for Entry.
2. Go to Create Entry on MTiOS.
3. Save it.
5. Get error for required field.
6. Input something for the field, tap Done.
7. Open the field again, remove everything you input at step 6.
8. Tap Save again.

Expected: Get error for required field.
Observed: Save entry.

**Comment by oguraayumi** [comment]
![portrait - webpage](https://cloud.githubusercontent.com/assets/618638/12473471/a53d5840-c055-11e5-8ea1-30a682608d00.png)
項目を、必須とoptionalのエリアに分けるとかはどうでしょうか。

または、必須の中にoptional項目が含まれる場合を考えて
必須部分を入力している最中にそのブロックのoptional項目を展開して出すとか…

@yuji

**Comment by cmatsuo** [comment]
required と optional で並びを分けてしまうと困るユーザーもいるのではないか、というかんじもしますが、どうですかねー？

**Comment by yuji** [comment]
@oguraayumi 本文、タイトルとかが枠組みの外にあるのでハテ？と思わないでもないかも。悩ましい・・・。先頭に * がやっぱり無難なんかなあ・・・
もう一発、アイディア出せますかね？

**Comment by cmatsuo** [comment]
Grab. I'll try this on again when https://movabletype.fogbugz.com/f/cases/112854/Data-API fixed.

**Comment by cmatsuo** [comment]
This issue fixed by https://movabletype.fogbugz.com/f/cases/112854/Data-API. Verified fix.
