### ISSUE TITLE
With "Author" permission, you cannot edit your entry 

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#139]
Steps:
1. Create an user who has Author permission for a blog.
2. Create an entry by that newly created user account at step 1.
3. Sign in to app with the user account.
4. Go to Manage Entries.
5. Click entry which you created at step 2.

Expected: Open Edit Entry screen.
Observed: Get permission error.

![author](https://cloud.githubusercontent.com/assets/546386/10505516/279bba34-7349-11e5-9f39-3383e0ab78f9.jpg)

**Comment by yuji** [comment]
Resolved Fixed!

**Comment by cmatsuo** [comment]
Verified fix!
