### ISSUE TITLE
Turn off iPhone kick you out of app

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#141]
Steps:
1. Sign in MTiOS.
2. Leave it as you had signed in.
3. Turn off your iphone.
4. Turn on and Open MTiOS.

Expected: Back to in MTiOS.
Observed: Open Sign in screen with filled account, password and URL. But when you tap sign in button, you'll get error as you can see attached image.

![signin](https://cloud.githubusercontent.com/assets/546386/10531935/0082fafc-73f3-11e5-8be3-5066a0cc9457.jpg)

FYI: You need to remove cache, delete MTiOS and get it again from DeployGate to sign in.

**Comment by yuji** [comment]
Still not reproduce.

**Comment by cmatsuo** [comment]
@yuji I can't repro this anymore. I don't know why but you cannot fix something unable to repro This case is close.
