### ISSUE TITLE
Submit unpublished entry and you can break entry status.

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#142]
Steps:
1. Create a scheduled unpublished entry.
2. On Manage Entries, make sure the entry unpublished and the icon is right one on on CMS.
3. Go to MTiOS and find the entry on Manage Entries.
4. Open Edit Entry, and make sure the status setting form does select nothing. All of Publish, Draft and Scheduled are white, I mean "off".
5. Don't edit anything. Just Tap Save, then Submit.
6. Go to Manage Entries on CMS, find the entry.

Expected: Nothing changed.
Observed: See attached image. Also, on Edit Entry, you'll find the status is now changed to "Draft", though it's still "Unpublished" on MTiOS. So, MT doesn't have right icon for this crooked status, thus display broken icon.

![status](https://cloud.githubusercontent.com/assets/546386/10532418/088d7f32-73f9-11e5-9f6d-4dc715464aac.jpg)

**Comment by cheebow** [comment]
status=Unpublishが返ってくるため。
UIを考える必要があるかも。

**Comment by yuji** [comment]
* 記事の編集画面についてUIを変更。
+ ステータスをいまのように並べるのではなく、他のフィールドと同じようにタップして選択させる方式に変更。
* ステータスが Unpublish な記事の場合だけ、ステータスのフィールドに "Unpublished" が追加され、選択される。
    * Unpublish 以外では、リストに存在しない。（選択可能な項目として出さない）

**Comment by cheebow** [comment]
対応しました

**Comment by yuji** [comment]
ステータスのUIはこちら
https://github.com/movabletype/smartphone-app/issues/151#issuecomment-179078021

**Comment by cmatsuo** [comment]
Verified fix.
