### ISSUE TITLE
Sometimes Sorting screen tend to down when save change

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#145]
This doesn't happen always but often enough. 

Steps:
1. Create all type custom fields for entry on CMS.
2. Sign in to MTiOS. 
3. Go to Edit Entry screen > Sorting (tap Edit on footer of Edit Entry).
4. Hide all items you can and change the order of rest of items.
5. tap Done of header.

Expected: Save change and back to Edit Entry.
Observed: MTiOS go down.

**Comment by cheebow** [comment]
@cmatsuo こちら、どうしても再現しません。その後再現していますか？

**Comment by cmatsuo** [comment]
@cheebow まだ再現しています。これも環境問題でしょうかねー。

**Comment by yuji** [comment]
うーむぼくのとこも再現しないな・・・

**Comment by cmatsuo** [comment]
@yuji mtqa4では起きなかった。ただし、発生しているテスト環境では、BooterでCFを一括作成していた。今回は手動で記事のCFだけ作成で試した。

**Comment by yuji** [comment]
@cmatsuo Booterか。もしかするとキャッシュかも。CF作ったらMT再起動かけないと認識おかしいから

**Comment by cmatsuo** [comment]
検証環境再起動で、再現しなくなりました。キャッシュだった。

**Comment by cmatsuo** [comment]
@yuji I can repro this issue with aws.

**Comment by yuji** [comment]
@cheebow I got crash report. Could you please investigate this? Thanks!
[export.txt](https://github.com/movabletype/smartphone-app/files/157985/export.txt)

**Comment by cheebow** [comment]
修正しました

**Comment by cheebow** [comment]
この状態から

![simulator screen shot 2016 03 04 18 18 22](https://cloud.githubusercontent.com/assets/153690/13522903/9753b218-e235-11e5-8fd4-8da4995cbb89.png)

この状態にすると100%落ちたので、

![simulator screen shot 2016 03 04 18 18 28](https://cloud.githubusercontent.com/assets/153690/13522908/9c6e6d24-e235-11e5-9cb8-9e393fc0ad2a.png)

これが大丈夫なように対応しました

**Comment by yuji** [comment]
@cmatsuo build104

**Comment by cmatsuo** [comment]
Verified fix! Thx!!
