### ISSUE TITLE
L10N: Do not have permission to delete an asset.

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#146]
This is when an user doesn't have Manage Asset permission but tried to delete an asset. (You need to remove the permission while the user have signed in to MTiOS to display Edit Asset screen)

@yuji Should I create this case to fbz instead of here? 

![asset](https://cloud.githubusercontent.com/assets/546386/10534877/67dc77b2-7418-11e5-932a-b7ab4d7c09c5.jpg)

**Comment by yuji** [comment]
hmm.. This message came from Data API...

Move to FogBugz. https://movabletype.fogbugz.com/f/cases/113531
