### ISSUE TITLE
unknown endpoint with MovableType 6.2

### ISSUE THREAD

**Issue by takkyun** [movabletype/smartphone-app#147]
Probably it's known issue.  

When I access movabletype v 6.2, I've got "Unknown endpoint" error as attached screenshot.

Even I saw the error, it seems that MTiOS is functional.

![simulator_screen_shot_19_10_2015_15_56_20](https://cloud.githubusercontent.com/assets/1464708/10568893/a940037c-767a-11e5-9ac6-ef519e8e2644.png)

When MTiOS access `/v2/sites/1/fields` of its data api access endpoint, server (movabletype 6.2) returns response with `404` and `Unknown endpoint` message.

To reproduce:
1. use MovableType v 6.2 (Data-API v3)
2. login with MTiOS, access site list
3. select one of sites

===

既知かもしれませんが、念のため。

MovableType v6.2 のサイトに MTiOS からアクセスした際に「Unknown endpoint」エラーが表示されます。表示された場合でもその後の操作は特に問題ないようですが。

MTiOS から data-api エンドポイントの `/v2/sites/1/fields`にアクセスした際、 404 のレスポンスが帰ってきています。

**Comment by yuji** [comment]
Thanks! Sometimes, this issue will happened...

**Comment by yuji** [comment]
I was not able to reproduce now with my MT... Will continue the investigation.

**Comment by takkyun** [comment]
Couldn't you? hmm... I will also check. Just FYI:

* I've Installed MovableType 6.2 newly in different path (not upgrade)
* Using Sqlite

===

再現できませんでしたか。参考までに

* MovableType 6.2 はアップグレードではなく、新規でインストールしました
* Sqlite を使っています（関係ないと思いますが）

こちらでも再確認してみます。

**Comment by cmatsuo** [comment]
@yuji @takkyun I also cannot repro this issue yet.

@takkyun Would you let us know your iPhone and OS version of yours? I'm basically using 5s with iOS9, btw.

**Comment by yuji** [comment]
一旦クローズします。再現したら新しくケースを開きます。
