### ISSUE TITLE
テキスト装飾：文字の選択範囲が２文字以下だと文字の装飾に失敗する。

### ISSUE THREAD

**Issue by ikoaoki** [movabletype/smartphone-app#150]
### 現象
アプリでのテキスト装飾で、文字の選択範囲が２文字以下だと文字の装飾に失敗する。

### 再現方法
1. アプリ上で「本文」を開き、「テキスト」ブロックを開く
2. 文字を入力する。

　例）　あああああ
　　　　いい
　　　　ううう

3. 文字を選択して、文字装飾ボタンを押す。

### 結果
4. 「あああああ」５文字、は文字装飾に成功する。
　「いい」２文字は、文字装飾ボタンを押した後、選択範囲が解除されるだけで、装飾に失敗
　「ううう」３文字は、文字装飾に成功する。（が、たまに失敗する）

**Comment by cheebow** [comment]
ZSSRichTextEditorの問題

**Comment by cheebow** [comment]
JS差し替えました

**Comment by yuji** [comment]
一旦確認願います

**Comment by ikoaoki** [comment]
こちら、ビルド88にて確認し、バッチリでした。
一文字でも二文字でも、文字の装飾に失敗する現象は確認出来ませんでしたので、こちらcloseいたします！
