### ISSUE TITLE
記事のステータスを示す、非公開（公開終了）アイコンが無い為に、未公開と区別が付きにくい。

### ISSUE THREAD

**Issue by ikoaoki** [movabletype/smartphone-app#151]
バグではなくリクエスト内容です。
公開が終了した記事を、また編集する機会は少ないと思いますので、重要ではないかもしれませんが。

### 要望
PC側では、ステータス「非公開（公開終了）」の記事はアイコンもあり分かりやすいが、
アプリ側では、「未公開」と同じ鉛筆アイコンがついており、区別がつきにくい。

### 画面の比較
「iPhoneから4」の記事が、指定日非公開により、「非公開（公開終了）」となった記事。

#### PCでの画面
<img width="891" alt="2015-10-19 18 37 07" src="https://cloud.githubusercontent.com/assets/6724607/10574353/74676968-7690-11e5-8c8a-f76b48c7541e.png">
（侵入禁止のようなアイコンがついており、二つ下の「未公開」の鉛筆アイコンと違う）

<img width="891" alt="2015-10-19 18 38 29" src="https://cloud.githubusercontent.com/assets/6724607/10574380/a0386236-7690-11e5-95d2-303ea391c818.png">
（画面右側に、ステータス、で「非公開（公開終了）」とぱっと見で分かる。

------

#### アプリでの画面
![mt-20151019181751-2](https://cloud.githubusercontent.com/assets/6724607/10574498/4c6aaf82-7691-11e5-9d84-34e7fae5e01e.jpg)
（未公開、と同じ鉛筆アイコンで区別ができない）

![mt-20151019183959](https://cloud.githubusercontent.com/assets/6724607/10574521/70153a88-7691-11e5-8bf9-c54d7e99948a.jpg)
（ステータスが、「公開」「未公開」「日時指定」のどれも選択されてない、だけで、ぱっと見では、「公開終了」という記事とはわかりづらい）

**Comment by oguraayumi** [comment]
![_guide](https://cloud.githubusercontent.com/assets/618638/12471169/745e1e1a-c03e-11e5-888d-8b0200033aba.png)
公開終了したもののアイコン作成しました。三段目、カレンダーにチェックマークがついているものです。ご確認くださいませ。
@yuji

**Comment by yuji** [comment]
@oguraayumi いいですね！
同じデザインでちょっと色ついたやつ。9x9 なgifファイルもMT本体用に本体用にあればと！

@cheebow status = UNPUBLUSH なものはこのアイコンを出すようにお願いします

**Comment by cheebow** [comment]
@oguraayumi 画像の作成をお願いします

**Comment by oguraayumi** [comment]
https://drive.google.com/open?id=0B3DAAwwej82XWGZya29iT1FqTGs
https://drive.google.com/open?id=0B3DAAwwej82XVjdNVUVMSnoyMnc
こちらにupしました。ご確認くださいませ。
@cheebow

**Comment by cheebow** [comment]
@yuji 修正しました。
segmentedControlが非選択状態になるのは、
https://github.com/movabletype/smartphone-app/issues/142
こちらですかね？

**Comment by oguraayumi** [comment]
![permalink](https://cloud.githubusercontent.com/assets/618638/12776248/c97be036-ca97-11e5-9af1-18457af4db63.png)
チケット、ここじゃないかもしれません。（すいません><）
公開ステイタスのタブをリストに変更しました。
@yuji

**Comment by yuji** [comment]
@oguraayumi あざます！ UI の部分は #142 の方でかな。と思っているのでそちらにコメントリンクしておきました。

**Comment by ikoaoki** [comment]
@yuji 高山さん、幾つかご確認をば。

「記事一覧」画面で、公開終了の新しいアイコンが表示されるのは、確認出来ました！

「記事の編集」画面で、「ステータス」タブが追加されたのは確認しましたが、
以下画像のように、
「ステータス　Unpublish」という表示はこれで問題ないでしょうか？
L10Nについては、https://github.com/movabletype/smartphone-app/issues/177　があること確認しておりますが、
関連issue　を辿ると

* 「公開ステイタス」という項目名になっていたり
* Unpublished　というステータス表示のコメントがあったり

と、ステータスの表示内容はこれでいいのかな？と少々気になりました。

![mt-20160205182111](https://cloud.githubusercontent.com/assets/6724607/12842385/c918853c-cc35-11e5-94e6-2664d7935585.jpg)

**Comment by yuji** [comment]
@ikoaoki 

> ステータスの表示内容はこれでいいのかな？

確認したいポイントは 英語だけどいいの？ この英語正しくなくない？ Unpublish ? Unpublished? どっちだ？

or 別件。と、どれでしょう・・。

**Comment by ikoaoki** [comment]
@yuji 

確認したいポイントは、

* Unpublish ? Unpublished? どっちだ？
　（https://github.com/movabletype/smartphone-app/issues/142#issuecomment-177831843
　　の高山さんのコメントに「Unpublished」という表現があるため、確認をしたく）

* 公開ステイタス？ステータス？　どっちだ？
　（デザイン段階での話、ということかもしれませんが、https://github.com/movabletype/smartphone-app/issues/151#issuecomment-179078021
　　のデザイン内で、「公開ステイタス」という表現になっているため）

という2点でしたm（＿＿）m

**Comment by yuji** [comment]
@ikoaoki こういった類の場合、CMS側ではどうなってるか？というのがだいたい答えになるです。なので：

> Unpublish ? Unpublished? 　どちらでしょう？

Unpublished が正解です。(End) と (Draft) も入れた方がいいか

> 公開ステイタス？ステータス？　どちらでしょう？

ステータスが正解です。

**Comment by ikoaoki** [comment]
@yuji 

高山さん、確認有難うございます。

> ステータスが正解です。
「ステータス」の表現が正解の旨、承知しました。
アプリ上で、「ステータス」表記を確認しました。

> Unpublished が正解です。(End) と (Draft) も入れた方がいいか
当方でもMT上での表記確認いたしました。
CMS側と合わせて、Unpublished(End) / Unpublished(Draft) に表記を合わせていただいた方がいいかと。

**Comment by yuji** [comment]
Draft はDraftとでているのでとりあえず文言は後日改めてまた。

@ikoaoki 確認がOKであればCloseで

**Comment by ikoaoki** [comment]
はい、こちら文言は別として、挙動としては確認出来ておりますので、closeさせていただきます。
