### ISSUE TITLE
未選択の画像ブロックは挿入できなくする

### ISSUE THREAD

**Issue by ikoaoki** [movabletype/smartphone-app#152]
こちらバグではなく、要望の範囲となります。

### 要望
記事/ページにアプリより入力時、テキストブロックや画像ブロックを見入力の場合。
未入力のテキストブロックは、「テキストを編集する」と出て分かりやすいのですが、
未入力の画像ブロックは、何も表示されないので、画像ブロックであると分かりづらいです。

#113　にて、CFで未入力時の表示について検討されているとのこと。同じタイミングで検討いただければ…。

![mt-20151020153612](https://cloud.githubusercontent.com/assets/6724607/10599912/6ecb60a2-7741-11e5-920b-6865389fa435.jpg)

**Comment by mt-backup** [comment]
そもそも、画像が設定されてないブロックを作らないようにする方が正解な気がする
2015年10月20日(火) 15:45 ikoaoki <notifications@github.com>:

> こちらバグではなく、要望の範囲となります。
> 要望
>
> 記事/ページにアプリより入力時、テキストブロックや画像ブロックを見入力の場合。
> 未入力のテキストブロックは、「テキストを編集する」と出て分かりやすいのですが、
> 未入力の画像ブロックは、何も表示されないので、画像ブロックであると分かりづらいです。
>
> #113 <https://github.com/movabletype/smartphone-app/issues/113>
> にて、CFで未入力時の表示について検討されているとのこと。同じタイミングで検討いただければ…。
>
> [image: mt-20151020153612]
> <https://cloud.githubusercontent.com/assets/6724607/10599912/6ecb60a2-7741-11e5-920b-6865389fa435.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/movabletype/smartphone-app/issues/152>.
>
-- 
--
Yuji Takayama
Movable Type Product Manager & Lead Engineer, Six Apart
ytakayama@sixapart.com

**Comment by cmatsuo** [comment]
+1 高山案（画像だけでなく、テキストでも同じ）

**Comment by cheebow** [comment]
修正しました

**Comment by yuji** [comment]
At Build 68

**Comment by ikoaoki** [comment]
こちら、「未選択の画像ブロック」が表示されないことを以下環境にて確認しましたので、closeいたします。
* MT for AWS 環境
* MTiOS ビルド68
* iPhone6s (iOS9.2)
