### ISSUE TITLE
PCとアプリで画像の作成ユーザー名の表示の種類が異なる

### ISSUE THREAD

**Issue by ikoaoki** [movabletype/smartphone-app#153]
細かい指摘ではありますが。

### 現象
PC側では、画像の作成ユーザーが「maoki」と＜ユーザー名＞で表示されるのに対し、
アプリ側では、画像の作成ユーザーが「アオキ」と＜表示名＞で表示される。

（ただ、アプリ側で「使いやすい」が条件ではあると思いますので、必ずしも絶対の統一の必要性は感じておりません）

##### PC側
<img width="815" alt="2015-10-20 18 32 33" src="https://cloud.githubusercontent.com/assets/6724607/10603572/b131022c-7759-11e5-8b59-c5044ddd9185.png">

##### アプリ側
![mt-20151020183118](https://cloud.githubusercontent.com/assets/6724607/10603581/bdf32620-7759-11e5-84bd-ddee7fcafa1d.jpg)

**Comment by mt-backup** [comment]
これは本来CMS側も表示名を使うべきところだな。。

2015年10月20日(火) 18:38 ikoaoki <notifications@github.com>:

> 細かい指摘ではありますが。
> 現象
>
> PC側では、画像の作成ユーザーが「maoki」と＜ユーザー名＞で表示されるのに対し、
> アプリ側では、画像の作成ユーザーが「アオキ」と＜表示名＞で表示される。
>
> （ただ、アプリ側で「使いやすい」が条件ではあると思いますので、必ずしも絶対の統一の必要性は感じておりません）
> PC側
>
> [image: 2015-10-20 18 32 33]
> <https://cloud.githubusercontent.com/assets/6724607/10603572/b131022c-7759-11e5-8b59-c5044ddd9185.png>
> アプリ側
>
> [image: mt-20151020183118]
> <https://cloud.githubusercontent.com/assets/6724607/10603581/bdf32620-7759-11e5-84bd-ddee7fcafa1d.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/movabletype/smartphone-app/issues/153>.
>
-- 
--
Yuji Takayama
Movable Type Product Manager & Lead Engineer, Six Apart
ytakayama@sixapart.com

**Comment by ikoaoki** [comment]
> これは本来CMS側も表示名を使うべきところだな。。

確かに同感ではあります…。
（だって、そもそも、ログインしたらPC側のヘッダーの右側に常に表示されているのは＜表示名＞だから）

ただ、何となく、1ユーザーとして「表示名」は、記事の「投稿者名」として出力されるhtml側に使うもので、
管理画面側では「ユーザー名」という使い分けの印象もありました。

**Comment by mt-backup** [comment]
ただ、何となく、1ユーザーとして「表示名」は、記事の「投稿者名」として出力されるhtml側に使うもので、
管理画面側では「ユーザー名」という使い分けの印象もありました。


その使い分けとも違って、MT的には、ユーザー名は

極力出さないようにするようにしてます。

サインインIDなので、あまし出さないように。

たまにこういうところに残ってますけど・・・。



2015年10月20日(火) 18:49 ikoaoki <notifications@github.com>:

> これは本来CMS側も表示名を使うべきところだな。。
>
> 確かに同感ではあります…。
> （だって、そもそも、ログインしたらPC側のヘッダーの右側に常に表示されているのは＜表示名＞だから）
>
> ただ、何となく、1ユーザーとして「表示名」は、記事の「投稿者名」として出力されるhtml側に使うもので、
> 管理画面側では「ユーザー名」という使い分けの印象もありました。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/movabletype/smartphone-app/issues/153#issuecomment-149498860>
> .
>
-- 
--
Yuji Takayama
Movable Type Product Manager & Lead Engineer, Six Apart
ytakayama@sixapart.com

**Comment by cmatsuo** [comment]
@yuji @ikoaoki これはクローズで、fbzへ移動でいいのではないでしょうか？

**Comment by mt-backup** [comment]
そですね。それで。
2015年10月21日(水) 10:29 Chieko Matsuo <notifications@github.com>:

> @yuji <https://github.com/yuji> @ikoaoki <https://github.com/ikoaoki>
> これはクローズで、fbzへ移動でいいのではないでしょうか？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/movabletype/smartphone-app/issues/153#issuecomment-149752884>
> .
>
-- 
--
Yuji Takayama
Movable Type Product Manager & Lead Engineer, Six Apart
ytakayama@sixapart.com

**Comment by yuji** [comment]
ということで、こちらはFbzにケースを作成して、こちらはCloseでお願いします

**Comment by ikoaoki** [comment]
有難うございます！
Fbzで、以下にて報告させていただきましたので、こちらcloseいたします。
https://movabletype.fogbugz.com/f/cases/113545/
