### ISSUE TITLE
アプリでは画像がファイル名では検索出来ない。

### ISSUE THREAD

**Issue by ikoaoki** [movabletype/smartphone-app#156]
仕様、ということではあるかもしれませんが。

### 現象
PCでは、画像の検索は「ファイル名」と「アイテム名」が対象になっているが、
アプリでは、「アイテム名」でしか検索が出来ない。

### 再現手順
アイテムに以下のようなファイルを用意しておく。
* アイテム名「飛行機」　ファイル名「space_shuttle03.jpg」
* アイテム名「飛行機」　ファイル名「airrace01.jpg」
* アイテム名「sky01.jpg」　ファイル名「sky01.jpg」
* アイテム名「sky03.jpg」　ファイル名「sky03.jpg」

##### PC側
* アイテム名「飛行機」　ファイル名「airrace01.jpg」
* アイテム名「sky01.jpg」　ファイル名「sky01.jpg」

##### アプリ側
* アイテム名「sky01.jpg」　ファイル名「sky01.jpg」

しか出てこない。

---
アプリ側では、アイテム詳細にもファイル名は出てきませんし、ファイル名で検索されないのは当然かな、と思いますが。一応ご確認までの意味を含めてをば。

**Comment by cmatsuo** [comment]
@ikoaoki 仕様書にあるとおり、仕様です。

**Comment by ikoaoki** [comment]
失礼しました。
仕様ということで、こちらcloseいたします!! :bow:
