### ISSUE TITLE
サイト/ブログを検索後に、Xボタンで全サイト/ブログを表示させると、一覧でブログに親ウェブサイト名が表示されないことがある。

### ISSUE THREAD

**Issue by ikoaoki** [movabletype/smartphone-app#157]
### 現象
ウェブサイト/ブログを検索後に、ウェブサイト/ブログの全一覧を再度出させる為に、
Xボタンを押して「検索」すると、
ウェブサイト/ブログの一覧は出ているが、ブログ名に親ウェブサイトが表示されたりされない。

### 再現手順
1. アプリにサインインする。
2. 検索ボックスに「site」などと入力し、検索する。
3. 検索語で絞られた一覧が出る。

4. 検索ボックスの　X　を押して、検索語を消してクリアし、空のまま「検索」する。
　（つまり、ここで、再度、ウェブサイト/ブログの全一覧を求める）

### 結果
5) ウェブサイト/ブログの一覧は出ているが、ブログ名に親ウェブサイトが併記されていない。

### メモ
再現頻度は高いようです。
…が、必ず、という訳ではなく、同じ手順でやっても表示されることもあったり、一部のブログのみが表示されていない、という結果が出たりもします。

リフレッシュすると、親ウェブサイト名が取得出来る時と、出来ないまま、の時があります。

![mt-20151021163030](https://cloud.githubusercontent.com/assets/6724607/10630432/6626701a-7811-11e5-8990-ada394e7fd21.jpg)

**Comment by yuji** [comment]
これ、普通に検索結果のブログにウェブサイト名がでていない。ということではないですかね。

**Comment by cmatsuo** [comment]
@yuji iOS9では見たことの無い現象ですね。

**Comment by ikoaoki** [comment]
@yuji 高山さん

そういった感じです。表現が上手く無かったようですが、「ブログに親ウェブサイト名」が表示されていない、ということです。

ただ、この現象も不安定で、全く同じ手順で、以下のように「一部のブログだけが、親ウェブサイト名が表示されていない」となる場合もあります。

![mt-20151022105836](https://cloud.githubusercontent.com/assets/6724607/10655053/132d618e-78ac-11e5-96c3-d005a3ee0a49.jpg)

**Comment by yuji** [comment]
表現悪くなく、理解してますｗ

ブログの下にウェブサイト名ですよね。
これ、検索するとボクのところでは間違いなく出てないんです。
最初の一覧と、検索フィルタ無しだと問題ないんですけど。

**Comment by cheebow** [comment]
@yuji これもMTクラウドでのみ発生するっぽいです

**Comment by yuji** [comment]
@ikoaoki MT AWS な環境ではどうでしょう？

**Comment by ikoaoki** [comment]
@yuji 高山さん

確かに、MT AWS な環境では、かなりトライしましたが、この現象は一度も再現しませんでした。
クラウドのQA1でテストするとかなりの再現性の高さで、クラウド環境で発生するもののようです。

**Comment by yuji** [comment]
環境問題の予感

**Comment by yuji** [comment]
アプリ側の問題とは考えにくいので、一旦クローズ
