### ISSUE TITLE
カテゴリを何もチェックしていない記事を保存しようとすると、Categories parameter is invaild.とアラートが出ることがある。

### ISSUE THREAD

**Issue by ikoaoki** [movabletype/smartphone-app#158]
関連 #128

iOS8 アプリversion 65 で発生しました。

### 現象

1. カテゴリを何もチェックしていない記事で、アプリ上で記事を「保存」＞「送信する」しようとする。
2. 「Categories parameter is invaild.」とアラートが出て、消える。
3.  再度「保存」＞「送信する」をするが、2　のアラートが繰り返し出る。

こちらも時折発生する現象ではありますが…。
このループになると、「カテゴリに何かチェックを入れる」までしないと、このループから脱出することができませんでした。

![mt-20151021173208](https://cloud.githubusercontent.com/assets/6724607/10631563/c2d770e0-7819-11e5-9d85-d516e07e8d91.jpg)

**Comment by yuji** [comment]
うーむ・・再現しない・・。

**Comment by yuji** [comment]
I guess I can reproduce this by save an existing entries. This issues is not bug of the App. Should be verify when Data API was solved.

**Comment by yuji** [comment]
6.2.4 であれば問題起きないはず

**Comment by ikoaoki** [comment]
こちら、
* 最新のdevelopにて
* アプリ　ビルド71
にて確認したところ、現象が再現しない事を確認しましたので、closeいたします！
