### ISSUE TITLE
サイト/ブログ検索後に「空」のウェブサイトが表示され、アクセスすると「unknown endpoint」とアラートが出る。

### ISSUE THREAD

**Issue by ikoaoki** [movabletype/smartphone-app#159]
関連　#147、#157

#157 にて高山さんと松尾さんからコメントいただいて、再度確認している時に、出会いました。

### 検証環境
* QA用MTクラウド （MT6.2）　qa1    
* 検証端末　iPhone4s - iOS 8.3　〜　アプリ バージョン65
* 検証端末　iPhone5c - iOS 8.4　〜　アプリ バージョン63

### 現象
サイト/ブログ検索後に、「空」のウェブサイトが表示され、
アクセスすると、「unknown endpoint」とアラートが出る。

二つの検証端末どちらでも同じ手順で発生しました。（MT6.2とiOS8の相性…？）

### 再現手順

1) アプリにサインインする。
　　http://QA1/mt/mt-data-api.cgi

2) サイト/ブログ　が一覧になっているところで、検索ボックスに「site」と入れて検索する。

　（class_site , First Website mt6qa1 , site10　とsiteを含むサイトがある）

3) 検索結果に、siteを含んだものが表示されず、「空の」検索結果が出る。

![mt-20151022113405](https://cloud.githubusercontent.com/assets/6724607/10655604/0e1e5b8a-78b1-11e5-91ee-0684a18f515d.jpg)

4) この空のサイトにアクセスしてみると、「unknown endpoint」とアラートが出る。

![mt-20151022113232](https://cloud.githubusercontent.com/assets/6724607/10655625/2d90b666-78b1-11e5-84bf-e3f858e381cb.jpg)

**Comment by cmatsuo** [comment]
@yuji Relate to #147 ?

**Comment by yuji** [comment]
I guess communication error (with data api) has occurred. However, I'm not sure why...

**Comment by cheebow** [comment]
@ikoaoki @yuji 
一度サインアウトしてから再度サインインしたらどうなりますか？
もしかすると6.2でパスワードの扱いが変わったことが影響しているのかもしれません。

**Comment by ikoaoki** [comment]
@cheebow @yuji 

今、もう一度テストをしてみました。
前回とは違う手順？で同じ現象が発生しました。

* QA用MTクラウド （MT6.2）　https://mt6qa1.sixapart.intra/mt/admin
* 検証端末　iPhone6s - iOS 9.2　〜　アプリ バージョン67

### 発生手順

1) アプリにサインインする。
　　http://mt6qa1.sixapart.intra/mt/mt-data-api.cgi

2) サイト/ブログ　が一覧になっているところで、検索ボックスに「site」と入れて検索する。

　（First Website mt6qa1 , site30, site40　とsiteを含むサイトがある）

3) 検索結果に、siteを含んだものが出る。

4) ３の検索結果が出た状態で、画面を下にひっぱり更新する。

5) 検索結果に、siteを含んだものが表示されず、「空の」検索結果が出る。（前回報告したのと同じ画面）

6) 時間を置いてもう一度、画面を下にひっぱり更新する。
7) ちゃんと　site　を含んだ検索結果がでる。

8) もう一度、画面を下にひっぱり更新する。

9) また「空の」検索結果が出る。（前回報告したのと同じ画面）

10) この「空の」サイトにアクセスしてみると、「unknown endpoint」とアラートが出る。

** この後何度か、検索結果画面をひっぱって更新すると、空になったり、ちゃんとした結果が出たり…（単純に通信の問題でしょうか？）　**

#### サインアウト後、もう一度サインインして、同じテスト

上記と同じ結果でした。

ただ、「一度出た検索結果が表示されている検索結果画面を、更新したら」「空の画面が出る」という結果で、最初から、「空の検索結果」は今回のテストでは出ませんでした。
検索結果を更新する人はそうはいないとは思うのですが…

ただ、6)〜10）の手順を繰り返すことで、空の検索結果が出たり出なかったり、なので、「最初からからの検索結果が出てしまう」ということもあるかもしれません。

**Comment by cheebow** [comment]
@yuji 返ってくるJSONが

```
[{

}, {

}]
```

となる時があるみたいです。
なんでしょうね。これ

**Comment by cheebow** [comment]
「Website」という文字列を含むサイトが3つあったとき

1.「We」で検索→空のJSON(NG)
2.「Web」で検索→3件のサイト(OK)
3.「We」で検索→3件のサイト(OK)

最初のWeでは失敗して、Webで成功するとその後のWeでも成功します。
キャッシュとかの問題でしょうか？

**Comment by ikoaoki** [comment]
@yuji @cheebow 

こちらでも、「Website」という文字列を含むサイトを三つ用意し、テストしました。
結果は、

1. 「We」で検索　→　３件のサイト
2. 「Web」で検索　→　空の結果
3. 「We」で検索　→　３件のサイト
4. 「Web」で検索　→　３件のサイト

（ここで成功すれば、この後も成功するか、と思ったが）

5. 「We」で検索　→　空の結果
6. 「We」で続けて二度検索するが、空の結果
7. 「Web」で検索　→　3件のサイト
8. 「We」 で検索　→　3件のサイト

9.  少し間を空けて（５秒程度）、「Web」で検索　→　空の結果

@cheebow さんのテストでは、最初に「We」で検索に失敗したのが、こちらでは成功。
その後、上記のように、空の検索結果が、一度きちんと３件のサイトが出る結果が、出てもまた失敗する結果が出たりして、傾向が掴めませんでした。

**Comment by yuji** [comment]
ちなみに、AWSなMTだとどうですか
クラウド固有の何かな気がしてきた

**Comment by ikoaoki** [comment]
こちら、高山さんのコメントを元に、
MT for AWS でテストしたところ、報告していた現象が再現せず。

MTクラウド側固有の問題であろう、ということでこちらcloseいたします！

**Comment by cmatsuo** [comment]
@yuji I could repro this with aws.

**Comment by cmatsuo** [comment]
Oops! There is another "unknown endpoint" case. This is dupe. I didn't need to reopen this!
