### ISSUE TITLE
When open Select primary category, category placed at the top of the list always has the star 

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#160]
It means, you always have to re-set primary category when you set some categories on the app.

Steps:
1. Go to Create/Edit Entry > category
2. On Select categories, select some categories, then tap Done.
3. On Select primary category, select undermost placed category, then tap Done.
4. Tap Category again, tap Done.

Expected: On Select primary categeory, the category you selected at step 3 marked with star. 
Observed: Category placed at the top of the list has star.

![pc](https://cloud.githubusercontent.com/assets/546386/10657707/6dc9f5c6-78ca-11e5-9b30-b6fc67821952.jpg)

FYI: You can go step 1 to 3 by CMS. 
FYI 2: This is harmless since you have to go to Select primary category screen when you set some categories, but it's better if you don't need to re-set it, anyway.

**Comment by cheebow** [comment]
修正しました

**Comment by yuji** [comment]
At Build 68

**Comment by cmatsuo** [comment]
verified fix.
