### ISSUE TITLE
iOS9.1: App doesn't display images anymore

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#161]
Steps:
1. Create a new website and publish it.
2. Sign in to app.
3. Upload image(s) from anywhere you want (Insert to an entry, page or just upload image to Assets).

Expected: You can see the image on edit screen and Manage Assets.
Observed: Image uploaded but you can't see the image thumbnail.

![images](https://cloud.githubusercontent.com/assets/546386/10684032/76e187a0-7983-11e5-9b56-442b35143dfa.jpg)

FYI: You get same result if you go through step 1 to 3 by CMS and check the result on the app. 
App can upload images, it just doesn't display it. 
FYI 2: You can see the images on the sites/blogs which you have previously used the features by app before. Though at first you gonna experience #130 (you can work around it by delete cache.)

**Comment by yuji** [comment]
hmm.... I was not able to reproduce this with my iPhone..

**Comment by yuji** [comment]
I guess environment issue. Not a stopper for this release.

**Comment by cmatsuo** [comment]
You mean, mt6qa3 is the problem...?

**Comment by cmatsuo** [comment]
@yuji I tried 3 test environments and I can repro this with all three. Is this mt6qa* issue? Do you have any test environment I can try out?

**Comment by mt-backup** [comment]
Can you try on our real cloud server that is mtqa4?

2015年10月26日(月) 9:52 Chieko Matsuo <notifications@github.com>:

> @yuji <https://github.com/yuji> I tried 3 test environments and I can
> repro this with all three. Is this mt6qa* issue? Do you have any test
> environment I can try out?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/movabletype/smartphone-app/issues/161#issuecomment-150994564>
> .
>
-- 
--
Yuji Takayama
Movable Type Product Manager & Lead Engineer, Six Apart
ytakayama@sixapart.com

**Comment by cmatsuo** [comment]
@yuji Ha! There is no problem with mtqa4. What's the problem of mt6qa*?

**Comment by mt-backup** [comment]
Hmm.... I'm not sure whats happened on mt6qa*......

2015年10月26日(月) 11:13 Chieko Matsuo <notifications@github.com>:

> @yuji <https://github.com/yuji> Ha! There is no problem with mtqa4.
> What's the problem of mt6qa*?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/movabletype/smartphone-app/issues/161#issuecomment-151002686>
> .
>
-- 
--
Yuji Takayama
Movable Type Product Manager & Lead Engineer, Six Apart
ytakayama@sixapart.com

**Comment by cmatsuo** [comment]
Okay. This case is close, but we need to know what's happning on mt6qa*.
