### ISSUE TITLE
iOS9.1: Category/Folder setting screen down app, though only the first time.

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#162]
We are experiencing #128 again, thought just for the first time.

It works fine second time, but since it's always down first time and there is no work around about it, I think this is stopper for 1.0.1. (Many people select category after write contents, right?)

Steps:
0. Website/Blog has categories or folders.
1. Sign in to app.
2. Go to create entry(/webpage).
3. Tap Category.

Expected: Open Select Category screen.
Observed: App go down.

4. Go to Create Entry screen again and tap Category, now you can see the screen this time.

**Comment by yuji** [comment]
grr.... I was not able to reproduce this on my iPhone6S + iOS 9.1... WTH....

**Comment by yuji** [comment]
still not reproduce...

**Comment by cmatsuo** [comment]
@yuji I can't repro this anomore. I tried out 3 test environments this morning.
