### ISSUE TITLE
Would be great if be able to insert Image block without upload when iPhone is offline.

### ISSUE THREAD

**Issue by yuji** [movabletype/smartphone-app#163]
''*iPhone is online*''

1. Sign in to MT.
2. Choose site, and make a new entry.
3. Now, you are on the new entry creation screen.

''*iPhone is offline* e.x. Airplane is take off''

4. Hit the Body field, then insert image field via Camera icon.
5. Take a photo, or choose an existing photo.

Actual: MTiOS says, "The operation couldn’t be completed."

Wish for: Image block (with selected image) will be inserted but file is not still uploaded. Then, the file will be uploaded before saving (send to server) a entry/page.

**Comment by cheebow** [comment]
@yuji これって#116で解決できますか？

**Comment by yuji** [comment]
@cheebow #116 は、記事への挿入じゃないほう（アイテム一覧からアップ）からなので、こっちとは別かなと。
こちらは、記事への挿入では1枚ずつだけど、即時にアップしないで記事の送信時に送る。って感じです。

**Comment by cheebow** [comment]
@yuji 画像が複数ある場合、記事の送信時、もし、途中でネットが途切れた場合を考えると結構悩ましいですね。画像がすべて送信し終わらないと、エントリ自体を保存できないわけで。
ちょっと、このあたりきちんと考える必要がありそうです。

**Comment by yuji** [comment]
@cheebow なるほど。要望としては理解できるので、なんとかしたいですね。次回の議題のひとつに

**Comment by yuji** [comment]
* 記事ブロックにアイテムを挿入したとき、回線状況の如何に関わらずリアルタイムのアップロードは行わない
* 記事を保存するとき、実行されるタスクと進行状況を表示する。また、ネットワークトラブルなどで途中で失敗した場合でも、レジューム出来る。
* 記事を保存する前は、アイテムブロックには選択された（あるいは撮影された）画像が表示されるのは現行と同じ

**Comment by cheebow** [comment]
https://github.com/movabletype/smartphone-app/issues/192
@oguraayumi  こちらに関連して、画像とデザイン仕様をお願いします

**Comment by oguraayumi** [comment]
仕様はこちらです。
https://app.zeplin.io/project.html#pid=56a70f84c53ee8e71c6043f7&sid=56cd2ab837497ae605d121ae
画像はこちらにupしました。
https://drive.google.com/open?id=0B3DAAwwej82XeU1ldUNlT2xmY28

@cheebow

**Comment by cheebow** [comment]
実装しました

**Comment by yuji** [comment]
@cmatsuo build 89

**Comment by cmatsuo** [comment]
@cheebow 
画像の挿入がある記事を作成して、MTへの送信前に記事をプレビューする（プレビューアイコンをクリック）と、意図せぬアップロードが始まってしまいます。

**Comment by cheebow** [comment]
@cmatsuo プレビュー時には画像がアップロードされている必要があるので、どうしても送信が必要になります。

@yuji この仕様で正しいですよね？

**Comment by yuji** [comment]
@cheebow 以前、ローカルのファイルでなんとか出来るかやってみる。みたいな話が有ったかとおもいますけど、あれはやっぱ難しいですかね。

あ、ブロックじゃないほうかこれは。

プレビューするために画像をアップロードします。続けますか？
的な確認出しますか。

**Comment by cheebow** [comment]
@yuji そうなんです。ブロックエディタはbase64で埋め込んでなんとかしたんですが、エントリのプレビューはテンプレートエンジンを通さなくてはいけないので、一度アップロードしないとカスタムフィールドの画像とかが展開されないので。

確認出す事はできます。
英語の文言いただけるとうれしいです！

**Comment by cmatsuo** [comment]
@yuji 
画像アップロードだけではなくて、記事の送信と同じようにアップローダー画面になって、記事の送信がスタートします。なので、

画像の挿入された記事をプレビューするには、記事を送信する必要があります。送信しますか？Y/N?

くらいはっきり、送信である旨を明示してしまったほうがいいかも。

**Comment by yuji** [comment]
@cheebow こんな感じで

Need to upload the images to make a preview.
Are you sure you want to continue a preview?

**Comment by cheebow** [comment]
実装しました

**Comment by yuji** [comment]
build 91

**Comment by cmatsuo** [comment]
@yuji 
上にも書きましたが、最初の私のコメントが勘違いによるもので、タイトルのみ入力（画像等無し）でもこのメッセージが表示されるので、動作として違和感があります。

"Need to upload the images to make a preview."　を、"images" > "entry" (もしくはPage)のようにしてはどうでしょう？

**Comment by yuji** [comment]
@cheebow 画像なしの場合でも送信が必要なのって前からでしたっけ？

**Comment by cheebow** [comment]
@yuji プレビューはAPI経由なので、どっちにせよ送信が必要です、よね？

**Comment by yuji** [comment]
@cheebow previewEntry に送信するという意味ではそうなんですけど、記事を保存しに行ってるわけではないですよね。そういう意味で言うと

=== ネット繋がってる ===
==== 未アップロードの画像がある場合 ====
画像がアップされちゃうよ。といことを伝える

    Need to upload the images to make a preview.
    Are you sure you want to continue a preview?

==== 画像がない場合 ==== 
何もださずにプレビュー作成、表示

=== ネット繋がっていない ===
前バージョンと同様

という感じでどうでしょう？

**Comment by cheebow** [comment]
@yuji アップロードのUIは共通にしたいので、画像がない時はアラートを出さないというのでどうでしょうか？

**Comment by cheebow** [comment]
@yuji こういう感じでどうでしょうか？

**Comment by yuji** [comment]
@cheebow はい。画像なしの場合はalert出さずにすすーっと行ってしまうでOKです！

**Comment by cheebow** [comment]
@yuji developにpushしてありますー

**Comment by yuji** [comment]
build 94

**Comment by cmatsuo** [comment]
Still reproducible. Though I'll check this again when #225 fixed.

**Comment by yuji** [comment]
@cheebow 

    @yuji アップロードのUIは共通にしたいので、画像がない時はアラートを出さないというのでどうでしょうか？

この部分ですが、「何もださずにプレビュー作成、表示」になったと思ったらアップロードだけはまだ出てるということですね。勘違いしてました。
v1 のころもアップロードってしてるんでしたっけ？previewEntry (without ID) のエンドポイント呼び出し時にデータを渡しているは渡していますが、アップロードというか。なのかなと思いまして。
イメージ的には、なに？サーバーに記事作られちゃうの？という感覚にもなるかなあと。

画像がない場合

アラートもアップローダーもださずにプレビュー作成、表示

というのが望ましいのですが、いかがなものでしょう

**Comment by cheebow** [comment]
@yuji 
v1の時は、プレビュー作成中のHUDが出てました。
このViewControllerのタイトルを「プレビュー作成」にしましょうか？
このいわゆる「アップロード」画面で、エントリの投稿、プレビューの作成も行っているので、できれば、この画面を表示したいのです。

**Comment by yuji** [comment]
@cheebow なるほど。
タイトル変えても、出るの一瞬だと思うので見えないかもｗ

アップローダーを出しながら、プレビュー作成中のHUDを出すというのは出来ますか？

**Comment by cheebow** [comment]
@yuji 
HUDが出るのも一瞬なのと、アップロードする画像が多いときHUDでプログレスが見えなくなっちゃうので厳しいかなと。

**Comment by yuji** [comment]
@cheebow
なるほど。したらばタイトルを変える方向でいきましょー。

Make preview...

これですかね。

**Comment by cheebow** [comment]
@yuji 記事作成のときは「Make Entry...」「Make Page...」にしますか？
画像アップロードのときは「Upload images...」ですかね

**Comment by yuji** [comment]
@cheebow 
そうですね。それでいきましょ。

**Comment by yuji** [comment]
@cheebow 
ごめんなさい。ちょいと変更で

Sending entry...
Sending page...
Upload images...

こちらで！

**Comment by cheebow** [comment]
修正しました

**Comment by yuji** [comment]
ありがとうございますー

**Comment by yuji** [comment]
build 95

**Comment by cmatsuo** [comment]
verified fix.
