### ISSUE TITLE
Would be great if user can configure image width freely.

### ISSUE THREAD

**Issue by yuji** [movabletype/smartphone-app#164]
## Specification
* A user will be able to specify any value as an image width as well as select a value from the list.
    * As a default setting.
    * In upload.

**Comment by cmatsuo** [comment]
@yuji 　> As a default setting.
Is this Compose Settings > Image default insertion options on CMS gonna be applied to MTiOS from 1.1?

**Comment by yuji** [comment]
If upper than 6.2.4 (not typo), default value come from CMS. Others, use MTiOS default. However, it is other feature.

In this sentence "As a default setting" means settings in MTiOS.

**Comment by cmatsuo** [comment]
Okay. thx! @yuji

**Comment by yuji** [comment]
@oguraayumi 

I imagine that I can enter free image width as follows:

1. Sign in.
2. Select a site from list.
3. Open a site settings.
4. Select a image size
5. You can see 7 items like Any size, Original, Large ... small
5.1. "Any size" is new one.
6. When user select "Any size" then slide to next screen.
7. In the next screen, user can enter any intger for image width.

**Comment by yuji** [comment]
* 画像サイズの一覧に選択項目として "カスタム" を追加
* "カスタム" を選択したとき、サイズの入力にすすむ
    * サイズは正の整数による入力のみ
    * 入力できるカスタムは、1サイト1つのみ
* "カスタム" が選択された場合、画像サイズの一覧の "カスタム” 選択項目に入力された数値を表記する。
    * "カスタム (600px)" という感じ
* 入力済みのカスタム項目の選択と数値の編集方法、UI検討が必要

**Comment by oguraayumi** [comment]
カスタムの項目を追加
入力前はプレースホルダー[任意のサイズをいれる(※ラベルは要検討)]
![portrait - select_category](https://cloud.githubusercontent.com/assets/618638/12782703/4913d8a8-cac0-11e5-8bc7-ee46aa7e6c4d.png)
カーソルを合わせるとキーボードが立ち上がる
![portrait - select_category2](https://cloud.githubusercontent.com/assets/618638/12782704/494e76c0-cac0-11e5-8f99-1a0bdd2c2f39.png)
数値を入力し終わると、チェックがはいっている
![portrait - select_category3](https://cloud.githubusercontent.com/assets/618638/12782783/cf4f52da-cac0-11e5-963f-0dd0fe64521a.png)

同じところをタップするとまたキーボードがたちあがる
別のサイズをタップするとチェックが移動する

チェックを前につけたほうがいいか？という点を悩んでいます。
@yuji

**Comment by yuji** [comment]
@oguraayumi おお、いいですね。こうなると、チェックマークは前のほうがいいかもですね

**Comment by oguraayumi** [comment]
他のページのチェックが右寄せだけど統一しなくて大丈夫だろうか…とまよっていましたが
先頭についているUIもデフォルトでありました。
チェックと頭にもってきました。
![portrait - select_category](https://cloud.githubusercontent.com/assets/618638/12871128/09afa06c-cdad-11e5-8088-98c3550d5249.png)
![portrait - select_category2](https://cloud.githubusercontent.com/assets/618638/12871126/09a30b86-cdad-11e5-88b3-be5e339bad50.png)
![portrait - select_category3](https://cloud.githubusercontent.com/assets/618638/12871127/09a3f258-cdad-11e5-853c-83d8f1764e35.png)
@yuji

**Comment by oguraayumi** [comment]
先頭にもってきました！
![portrait - select_category](https://cloud.githubusercontent.com/assets/618638/12871133/59c5dfda-cdad-11e5-96a4-3510a6c1c71d.png)
![portrait - select_category2](https://cloud.githubusercontent.com/assets/618638/12871135/5a139e1e-cdad-11e5-8adc-62d3825bee7d.png)
![portrait - select_category3](https://cloud.githubusercontent.com/assets/618638/12871134/5a127c0a-cdad-11e5-974d-a70734d4445e.png)
@yuji

**Comment by yuji** [comment]
@cheebow これでどうでしょ！

**Comment by cheebow** [comment]
@oguraayumi チェックを前につけるなら、チェックマークの画像が必要になりますので、用意をお願いします。

**Comment by oguraayumi** [comment]
チェックマークupしました。
https://drive.google.com/open?id=0B3DAAwwej82XeU1ldUNlT2xmY28
zeplin
https://app.zeplin.io/project.html#pid=56a70f84c53ee8e71c6043f7&sid=56baf203179c309c0bbd10b1

@cheebow

**Comment by cheebow** [comment]
@oguraayumi @yuji 実装を始めたんですが、一度入力してしまうと、カスタム以外のところと見え方が同じになってしまって、再入力の方法がわかりにくい気がしました。
そこで、カスタムには常に入力ができるよということがわかるUIにしたほうが良いのではないかと思うのですが、どうでしょうか？

![simulator screen shot 2016 02 16 9 31 18](https://cloud.githubusercontent.com/assets/153690/13063884/3a75ac34-d490-11e5-9e16-0a3a05e0f766.png)

**Comment by yuji** [comment]
@cheebow @oguraayumi 枠付きのほうがいいですねー

**Comment by cheebow** [comment]
実装しました

**Comment by yuji** [comment]
build 78

**Comment by cmatsuo** [comment]
@cheebow 
1. 新しくカスタムサイズの値を入力した場合、自動的にチェックもカスタムを選択（移動）するようにできませんか？
2. カスタムを選択したけれども、カスタムサイズの値が未入力の場合、完了をタップしても保存できない（エラーを表示）するようにできませんか？（現在は自動的に5px となる）

**Comment by cheebow** [comment]
修正しました

**Comment by yuji** [comment]
build 79

**Comment by cmatsuo** [comment]
上記、カスタムサイズの未入力と、チェックの移動については、修正を確認済み。

**Comment by cmatsuo** [comment]
@cheebow 
以下の件が、iOS8だとうまくいかない場合があります（一度別のものを選択していると移動するが、最初に選んだのがカスタムのフォームだと、移動しない）。iOS9では問題ないのですが。ちと、見てみていただけますか？

>1. 新しくカスタムサイズの値を入力した場合、自動的にチェックもカスタムを選択（移動）

**Comment by cheebow** [comment]
@cmatsuo フィールドにフォーカスが来ると項目が選択されるという動作なんですが、標準の方法では難しく(チェックをつけた瞬間にキーボードが閉じてしまって入力できない)そのためイレギュラーな方法をとっています。それが、OSのバージョンによって動かない時があるのかもしれません。
今回解決できたとしても、今後のOSでも使えるかどうかわからないので、この機能自体を取りやめるか、逆に項目を選択すると入力フィールドにフォーカスが当たるというようにするというのもありかと。
@yuji どうでしょう？

**Comment by cmatsuo** [comment]
@cheebow @yuji 
私が入力フォームのところをタップするという動作をしていたので、上記のような修正のお願いになったのですが、もしかしたら、逆の、「項目を選択すると入力フィールドにフォーカスが当たる」という動作も、利用者側から見るとほぼ同様に見える動作にあたるかも。

**Comment by yuji** [comment]
@cheebow 項目の選択でフィールドにフォーカスでOKだと思います！

**Comment by cheebow** [comment]
対応しました

**Comment by yuji** [comment]
build 84

**Comment by cmatsuo** [comment]
おおお。8ではいい感じになるけれども、9ではフォームを叩くと、チェックの移動をしなくなりますね。

@cheebow 
appleの調べによると、現在iPhoneユーザーの8割近くはOS9ユーザーだそうで、 @yuji と相談の上、今回はOS9ユーザー合わせがベターだろうということになりました。
すみません。修正1個前の、 「フィールドにフォーカスが来ると項目が選択される」動作に戻していただけますか？

**Comment by cheebow** [comment]
修正しました

**Comment by yuji** [comment]
build 85

**Comment by cmatsuo** [comment]
verified implements.
