### ISSUE TITLE
Displaying version in the App.

### ISSUE THREAD

**Issue by yuji** [movabletype/smartphone-app#165]
Or, any ideas for how to know my app version.

**Comment by yuji** [comment]
Screen Design

**Comment by oguraayumi** [comment]
![blog_setting_size](https://cloud.githubusercontent.com/assets/618638/12471101/95f5063e-c03d-11e5-8852-c8a8b6134f74.png)
すこしグレーの文字でいれてみました。
@yuji

**Comment by yuji** [comment]
@oguraayumi 
唐突感がありますかね。


Movable Type for iOS ver. 1.1.0

んー冗長か・・・。


@cheebow 
ここのバージョン番号自体は、プロジェクトのプロパティで指定している Version の値出せますか？
Build のほうがいいかな。でも、Storeに並んだらみんな同じ Build 番号のはずだから Version だけでいいのか。

**Comment by oguraayumi** [comment]
![blog_setting_size](https://cloud.githubusercontent.com/assets/618638/12473452/7d437892-c055-11e5-935a-e0c7d8c3826b.png)
Movable Type for iOS ver. 1.1.0にして、なじむよう、グレーを少し薄くしました。
@yuji

**Comment by cheebow** [comment]
@yuji バージョン出せます！

**Comment by yuji** [comment]
@oguraayumi @cheebow いい感じですかね！

**Comment by cheebow** [comment]
@oguraayumi 色やフォントサイズの情報をください

**Comment by oguraayumi** [comment]
https://app.zeplin.io/project.html#pid=56a70f84c53ee8e71c6043f7&sid=56a71689350a876b6624d99a
こちらでお願いいたします
#9B9B9Bです。
@cheebow

**Comment by cheebow** [comment]
実装しました

**Comment by cmatsuo** [comment]
verified fix.
