### ISSUE TITLE
未入力のテキストブロックが、編集完了後に編集画面に戻ると「を編集する」という文言になっている。

### ISSUE THREAD

**Issue by ikoaoki** [movabletype/smartphone-app#167]
https://github.com/movabletype/smartphone-app/issues/152
上記issues のチェック中に遭遇しました。

### 現象
記事編集画面で、テキスト未入力のテキストブロックで、編集を完了し、その後、再度編集画面に戻ると、未入力のテキストブロックに「を編集する」という表示になっている。

### 確認環境
* MT for AWS 環境
* MTiOS ビルド68
* iPhone6s (iOS9.2)

### 再現手順
1. MTiOS よりサインインする。
2. ブログ（ウェブサイト）に移動する。
3. 右上の作成アイコンより「新しい記事」を選択して、記事作成画面に行く。
4. 「本文を編集する」をクリックして、編集画面に行く。
5. テキストアイコンをクリックする。
6. 何も入力しないまま、＜　で前の画面に戻る。
7. この時、本文編集画面では「テキストを編集する」とテキスト未入力ボックスは表示されている。
8. 右上の「完了」を押す。
9. 記事編集画面に戻ったら、もう一度「本文を編集する」をクリックする。
10. 編集画面で、先ほどのテキスト未入力ボックスが、「を編集する」と表示されている。

### 期待する結果
10 にて、「テキストを編集する」と表示されている。
（上記に「本文」とスコープタイトルが表示されているので、「本文」「を編集する」と見れもしますが、「を」から始まる案内文は違和感があります。）

![mt-20160125134712](https://cloud.githubusercontent.com/assets/6724607/12542746/7f89beb4-c36a-11e5-8d88-35c74704a12f.jpg)

**Comment by cheebow** [comment]
修正しました

**Comment by ikoaoki** [comment]
こちら、ビルド71にて、「テキストを編集する」と表示されること、確認いたしました！
