### ISSUE TITLE
L10N: 1.1 new feature and fix

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#168]
* 'Unpublished on' dates should be dates in the future. (relate to #104 )
![img_0102](https://cloud.githubusercontent.com/assets/546386/12572432/d2da104e-c42f-11e5-8440-939342dbfdbb.jpg)

**Comment by cmatsuo** [comment]
* You must set a valid Local file Path. (relate to #122 )
![img_0103](https://cloud.githubusercontent.com/assets/546386/12572547/399dfb96-c431-11e5-8239-5da74e88d050.jpg)

**Comment by cmatsuo** [comment]
(relate to #110 )
"This app does not have access to your photos or videos.
You can enable access in Privacy Settings."
![img_0105](https://cloud.githubusercontent.com/assets/546386/12602415/82c91aa6-c4ec-11e5-9531-0e797e890d8a.jpg)

**Comment by cmatsuo** [comment]
* Uploader - 画像の複数アップロードしている最中の画面

**Comment by cmatsuo** [comment]
Relate to #164
* Custom
* Any size

![size](https://cloud.githubusercontent.com/assets/546386/13138333/d5544b54-d669-11e5-8fda-d5a8ef6c92c1.jpg)

**Comment by cmatsuo** [comment]
relate to #193
* You can upload 8 photos at once.

![8photos](https://cloud.githubusercontent.com/assets/546386/13166801/819ffb4c-d70f-11e5-8ff0-e67b0c42717d.jpg)

**Comment by cmatsuo** [comment]
When you not enter custom size, or enter too small/huge value, you'll get this message.
* Please enter a custom size.

![pleaseentrt](https://cloud.githubusercontent.com/assets/546386/13208228/fe54f0ce-d959-11e5-97a1-7d83ad6332b1.jpg)

**Comment by cmatsuo** [comment]
再構築を一度もしていないブログ／ウェブサイトにアップロードを行った場合のアップロードエラー文言

* Image upload
* There is the rest of the items , you sure that you want to upload again?
* YES
* NO

![imageupload](https://cloud.githubusercontent.com/assets/546386/13314095/7743b306-dbe6-11e5-91fb-10127a8927f3.jpg)


上記のエラーで、YESをクリックした場合

* Upload error

![upload error](https://cloud.githubusercontent.com/assets/546386/13314100/7ba0f062-dbe6-11e5-8b53-4c06ccc97f6b.jpg)

**Comment by cmatsuo** [comment]
* You must set a vaild path.

![validpath](https://cloud.githubusercontent.com/assets/546386/13345661/fdd17a26-dca3-11e5-8d40-15a7322de821.jpg)

**Comment by cmatsuo** [comment]
When you upload untitled Entry/Page
* Entry
* Page

![untitles](https://cloud.githubusercontent.com/assets/546386/13384079/6c3e4a06-ded5-11e5-91b2-bd9a7d5b6581.jpg)

**Comment by cmatsuo** [comment]
* Upload Error
* Do not have permission to create an entry.

![permission](https://cloud.githubusercontent.com/assets/546386/13415850/abe9412a-dfa1-11e5-895a-51903ccbad60.jpg)

**Comment by cmatsuo** [comment]
When you don't have permission for upload image.
* Upload Error
* Do not have permission to upload.

![permissiontoupload](https://cloud.githubusercontent.com/assets/546386/13418578/154c95fa-dfba-11e5-86c9-5b747649a566.jpg)

**Comment by cmatsuo** [comment]
When user doesn't have permission for the website.
* Do not have permission to retrieve the requested fields.

![donothave](https://cloud.githubusercontent.com/assets/546386/13448178/39b355b4-e064-11e5-9f1c-02c4e80b1362.jpg)

**Comment by yuji** [comment]
https://github.com/movabletype/smartphone-app/commit/14c9782b2c8249b2dcb5312c67d29ab7e44cd043

**Comment by cmatsuo** [comment]
長くて紛らわしくなってきたので、今後のものは #234 へ。
このチケットはクローズ。
