### ISSUE TITLE
DropDown/RadioButton CF: 「オプションの選択をして下さい」エラー

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#170]
Steps:
1. Create Drop Down Menu/Radio Button custom field like following:
* System Object: Entry
* Type: Drop Down Menu (or Radio Button)
* Options: booter, biddle, trizzle

2. Make sure the CF isn't required, Save it.
3. Go to MTiOS > Create Entry.
4. Just click Save and send it to MT.

Expected: Send to MT.
Observed: Got error:
 
![img_0106](https://cloud.githubusercontent.com/assets/546386/12604002/a774defe-c4fa-11e5-9b42-49f476c98e94.jpg)

**Comment by yuji** [comment]
Maybe cause by https://movabletype.fogbugz.com/f/cases/112854/. Please try again when that case has been resolved.

**Comment by cmatsuo** [comment]
Verified MT does permit empty value for not required fields.
Also, for DropDown/RadioButton, MT does permit empty value even for required fields. This is spec for now. See https://movabletype.fogbugz.com/f/cases/112854/
