### ISSUE TITLE
Add Markdown support.

### ISSUE THREAD

**Issue by yuji** [movabletype/smartphone-app#172]
Spec is here: https://github.com/movabletype/smartphone-app/wiki/v1_1_0#markdown-support

**Comment by cheebow** [comment]
@yuji クライアントではなにをすればよいのでしょうか？

**Comment by yuji** [comment]
* エディタの設定 ->  Markdown を追加。選択可能に
* "本文"と"続き"でのみMarkdown 入力となる
* エディタにMarkdown入力であることがわかるようにする
* エディタが Markdown であるときは、新規保存するとき記事の Entries.format を "markdown" とする
* MTに保存されている記事(Entries.format = "markdown" || "markdown_with_smartypants")を編集で開く場合、新規のブロックと同じく、Markdown エディタとなる
* 新規記事のPreview は、Markdown をローカルで HTML に変換してプレビューを表示する
    * うまいライブラリがあれば

**Comment by cheebow** [comment]
@yuji 
このライブラリで互換ありますかねぇ
https://github.com/mdiep/MMMarkdown

**Comment by yuji** [comment]
オリジナルのPortじゃない。とか書いてますけど、どこまで実装されているかですね。ともあれ、他の拡張ライブラリとかじゃなく、ピュアなMD実装っぽいのかなあ。であれば、互換性はいいと思います。

**Comment by cheebow** [comment]
@yuji 

> MTに保存されている記事(Entries.format = "markdown" || "markdown_with_smartypants")を編集で開く場合、新規のブロックと同じく、Markdown エディタとなる

とありますが、format="markdown"のときbodyにはHTML化されたものが入ってきます。

**Comment by cheebow** [comment]
@yuji 記事取得時に「no_text_filter」を使うことで解決しました

**Comment by mt-backup** [comment]
あーそうでした。API経由だとrawdataじゃなかった

2016年2月3日(水) 12:34 Motokazu Sekine <notifications@github.com>:

> @yuji <https://github.com/yuji> 記事取得時に「no_text_filter」を使うことで解決しました
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/movabletype/smartphone-app/issues/172#issuecomment-178982561>
> .
>
-- 
--
Yuji Takayama
Movable Type Product Manager & Lead Engineer, Six Apart
ytakayama@sixapart.com

**Comment by cheebow** [comment]
@yuji preview APIでEntry.format="markdown"にしても、Markdownのまま表示されちゃうんですがなにか方法ありますか？

**Comment by yuji** [comment]
@cheebow ああ・・逆に送られたものをそのまま使っているからか・・convertする仕組みがいまないかもですね・・

**Comment by cheebow** [comment]
@yuji このpreviewはビルドされたものと同じものが表示されるはずなので、クライアントでコンバートしてから送るってのはないですよね。

**Comment by cheebow** [comment]
実装しました

**Comment by yuji** [comment]
QA:

* 新規記事を Markown で作成可能
* 既存の Markdown の記事を Markdown で編集可能
* テキストブロックのプレビューでHTMLに変換された結果を見れる

というところかしら

**Comment by cmatsuo** [comment]
verified implements.
