### ISSUE TITLE
Should respect default upload destination that configured in the MT.

### ISSUE THREAD

**Issue by yuji** [movabletype/smartphone-app#173]
Spec is here: https://github.com/movabletype/smartphone-app/wiki/v1_1_0#upload-destination

**Comment by cheebow** [comment]
@yuji v3以上のAPIだと標準のアップロード先が帰ってくるということですか？　このあたりをまとめたドキュメントってありましたっか？

**Comment by yuji** [comment]
@cheebow v3.01 以降ですね。MT的に言うと今度出る予定の6.2.4以降です。
そのバージョンの場合、/v3/sites/1 とかで Sites リソースを取ってくるとユーザーが設定したデフォルトアップロードパス or サイトパスが uploadDestination.path で取得できるので、MTiOS側でデフォルトアップ先が指定されていなければそれを使う。
で、allowToChangeAtUpload が true だった時は、アップロード時にユーザーがアップ先を変更可能なので、MTiOSでもアップ先を変えること出来る。false だったときは、管理者が変更を許可していないので、アップ時、デフォルト設定時には uploadDestination.path を変えさせない。
という感じです。

**Comment by cheebow** [comment]
@yuji 

MT6.2.4 (Data API v3.01) 以降の場合についてですが、

「MTiOS 側に設定がない場合」
これは、厳密には判断できないんですが初期値が「/」なので、「/」であれば設定がないとして良いでしょうか？

「MTの設定 (Sites.uploadDestination.path) の値を値を採用する」
これは、アップロード時に指定するだけでしょうか？　それとも、MTiOSの設定自体を変えて保存してしまう？

MT側がアップロード先の変更を許可していない場合「MTのアップロード先が利用される」
これでも、アップロード時だけでしょうか？　それとも、MTiOSの設定自体を変えて保存しますか？

**Comment by cheebow** [comment]
@yuji これ、保存しても保存しなくてもサイト情報取るたびに書き換わるので、保存して良さそうですね。Sites.allowToChangeAtUpload = trueの時は、MTiOSの設定優先ですし。

**Comment by cheebow** [comment]
実装しました

**Comment by yuji** [comment]
@cheebow 遅レスすいません

> 「MTiOS 側に設定がない場合」
> これは、厳密には判断できないんですが初期値が「/」なので、「/」であれば設定がないとして良いでしょうか？
はい。/ のときでよいかと

> 「MTの設定 (Sites.uploadDestination.path) の値を値を採用する」
> これは、アップロード時に指定するだけでしょうか？　それとも、MTiOSの設定自体を変えて保存してしまう？
> MT側がアップロード先の変更を許可していない場合「MTのアップロード先が利用される」
> これでも、アップロード時だけでしょうか？　それとも、MTiOSの設定自体を変えて保存しますか？
保存しちゃうでOKですね

**Comment by yuji** [comment]
QA:
* MT6.2.3 以前
** MT側でデフォルトアップロード先が設定されていてもいなくても、MTiOS のアップロード設定が有効。（サイト単位のデフォルト設定、アップロード時の設定）

* MT6.2.4 以降
** MT 側でデフォルトアップロード先が設定されていない
*** MTiOS のアップロード設定が有効。（サイト単位のデフォルト設定、アップロード時の設定）
** MT 側でデフォルトアップロード先が設定されていて、変更可能
*** MTiOS のアップロード設定が有効。（サイト単位のデフォルト設定、アップロード時の設定）
** MT 側でデフォルトアップロード先が設定されていて、変更不可
*** MT 側のアップロード先が有効（サイト単位のデフォルト設定、アップロード時の設定）

ってとことかしら

**Comment by cmatsuo** [comment]
@cheebow 
6.2.2で、CMSの変更可・不可設定に関わらず、アプリでは変更付加（グレイアウト）になります。

**Comment by cheebow** [comment]
修正しました

**Comment by yuji** [comment]
@cmatsuo build 75にて

**Comment by cmatsuo** [comment]
verified fix.

**Comment by yuji** [comment]
@cheebow こちら、本機能を一旦とりやめようとおもいます。

**Comment by yuji** [comment]
@cheebow 変更の revert はこのチケットにします？それとも別に起こします？ どちらでも構いませんけど

**Comment by cheebow** [comment]
@yuji このままで大丈夫です。
戻しました。

**Comment by yuji** [comment]
build 85

**Comment by cmatsuo** [comment]
@cheebow 
CMSでパスの変更を許可しない設定にしていると、パスの編集が出来ない、という部分だけ残ってしまっています。編集の許可／不許可についても、CMSの設定を持ってこないようにお願いします。

@yuji 
このリバート、CMSの設定と、アプリの設定を完全に区別する（アプリはCMSの設定を一切無視する）状態にするということでOKですよね？

**Comment by yuji** [comment]
@cmatsuo @cheebow 

> このリバート、CMSの設定と、アプリの設定を完全に区別する（アプリはCMSの設定を一切無視する）状態にするということでOKですよね？

はい。v1.0.1の状態に戻す感じです。

**Comment by cheebow** [comment]
すみません！抜けてました。
修正しました。

**Comment by yuji** [comment]
build 87

**Comment by cmatsuo** [comment]
CMS側で、アップロードパスの「変更を認めない」状態の場合、アプリ側の設定に関わらず、CMSでのパスの設定先にアップロードされる

@yuji 
DeployGate #67 で確認したところ、1.0.1ではCMSでの確認を全く無視するという仕様でした。
1.0.1に戻すという認識でしたが、もしかしてCMSの設定を守るのが正しいのか？仕様としてはどちらでしょう？

**Comment by yuji** [comment]
@cheebow @cmatsuo CMS側の変更許可のフラグも前の状態に一旦戻しましょう。ユースケースを詳しく考えてからになりますが、モバイルアップロードは別口。とかあるかもしれないとか思ったので

**Comment by cheebow** [comment]
@yuji アプリ側では元の状態に戻っていると思うのですが、CMS側で変更不可の時は、強制的にCMS側のパスが使われるということはありませんか？

**Comment by yuji** [comment]
@cheebow そうだ。そうでした。Data API もCMSの設定をリスペクトしてます。

@cmatsuo ごめんなさい。すっかり忘れてましたが・・・。CMS側で許可しないようにしている場合は、強制的にCMS側のパスにアップされます。

**Comment by cmatsuo** [comment]
@yuji 了解。
