### ISSUE TITLE
L10N: ステータス

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#179]
On Create/Edit screens, and Status Setting screens.
* Publish
* Draft
* Future
* Unpublish

![status](https://cloud.githubusercontent.com/assets/546386/12838682/7624b3ee-cc14-11e5-85a5-498e5599ba26.jpg)

![edit](https://cloud.githubusercontent.com/assets/546386/12838668/5385dd54-cc14-11e5-9738-d24903393c68.jpg)

**Comment by yuji** [comment]
@cheebow これ、APIから返ってくる値がこれなんですが、transにかけることってできますかね？
MT だと計算結果を trans する場合は、コメントアウトした trans('foo') を要しいておいて、辞書作成には回しておいて、実行時は普通に trans($var)みたいな感じでやっていますかね

**Comment by cheebow** [comment]
修正しました

**Comment by yuji** [comment]
おお、もともと用紙された！すてき。

**Comment by yuji** [comment]
用紙ってなんだ。用意。

**Comment by yuji** [comment]
@cmatsuo build 105

**Comment by cmatsuo** [comment]
verified fix.
