### ISSUE TITLE
Display selected status on Unsent Entries/Pages as well as Entries/Pages lists

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#180]
Steps:
1. Create an Unpublished entry.
2. Open Edit Entry screen.
3. Edit the status to, for example, Draft, and Save the entry to Local.
4. View Unsent Entries screen.

Expected: That entry's status is Draft.
Observed: Entry's status is Unpublished.

Note to self: Check newly created entries's status as well. They also should display selected status.

**Comment by yuji** [comment]
Always should displaying *current* status.

**Comment by cheebow** [comment]
修正しました

**Comment by yuji** [comment]
@cmatsuo build 75にて

**Comment by cmatsuo** [comment]
verified fix.
