### ISSUE TITLE
Want default Editor Format setting 

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#182]
User who use Markdown almost always use markdown, I think.
For now, if you want to use Markdown, you have to change the format every time you start create an entry/page. Want default setting screen for editor format.

**Comment by yuji** [comment]
@cheebow @oguraayumi サイトの設定のところに、デフォルトのエディタを設定できる仕組みを入れるといいかなと。

**Comment by yuji** [comment]
サイトの設定に追加

ラベル: Editor (JA: エディタ)
値: リッチテキスト, プレーン, Markdown

記事・ページの新規作成時、エディタがデフォルトのものになる。記事・ページ単位での変更は可能（まま）

@oguraayumi デザインおねがいします

**Comment by oguraayumi** [comment]
![blog_setting_guide](https://cloud.githubusercontent.com/assets/618638/13135696/89dbee10-d656-11e5-885b-76d5ca4e9744.png)
@yuji 
作成しました。ご確認ください。

**Comment by yuji** [comment]
@oguraayumi おー。
@cheebow こちらで。

**Comment by cheebow** [comment]
@oguraayumi アイコンをくださいませ

**Comment by oguraayumi** [comment]
お待たせして申し訳ありません。
こちらにupしました。
https://drive.google.com/open?id=0B3DAAwwej82XeU1ldUNlT2xmY28

サイズ等は下記をご確認くださいませ。
https://zpl.io/Z1Jbn88

@cheebow @yuji

**Comment by cheebow** [comment]
実装しました

**Comment by yuji** [comment]
build 90

**Comment by cmatsuo** [comment]
@yuji 
画像にある「配置」の実装は入るのでしょうか？絵だけ？

**Comment by yuji** [comment]
@cmatsuo あ、これは記事の設定のスクショだ。サイト側でデフォルトの配置設定は今のところ実装予定ないですね

**Comment by yuji** [comment]
NG: 記事の設定
OK: アップロード時の設定

**Comment by cmatsuo** [comment]
verified implement.
