### ISSUE TITLE
If you create an entry/page with Plain/RichText format, You cannot edit it anymore.

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#183]
Relate to #172 

Steps:
1. Create an entry with RichText format, send it to MT.
2. Go to Entries screen.
3. Select the entry which you created at step 1.
4. Tap Body.

Expected: Open Edit Body screen.
Observed: Cannot move to Edit Body screen.

FYI: If you create the entry with Markdown, you can open the edit screen.

**Comment by cheebow** [comment]
修正しました

**Comment by yuji** [comment]
@cmatsuo build 75にて

**Comment by cmatsuo** [comment]
verified fix.
