### ISSUE TITLE
Display Editor Mode setting form on Advanced Setting for Sent Entries/Pages

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#184]
Relate to #172

Steps:
1. Open Create an Entry.
2. Open Advanced Setting screen.
3. Make sure you can find Editor Mode setting form.
4. Back to create entry screen, create an entry, send it to MT.
5. Go to Entries.
6. Select the entry you created at step 4.
7. Open Advanced Setting screen.

Expected: Find Editor Mode setting form.
Observed: Cannot find ind Editor Mode setting form. (Because the app didn't need it before for the sent entries/pages.)

**Comment by cheebow** [comment]
@yuji 既存のエントリは、plain/richともにHTMLエディタだったので、エディタモードがなかったと思うんですが、どうしましょう？
ここは、MTiOS側で変えられなくてもいいのかなって気もするんですけど。RichEditorにして、HTML壊しちゃうのが怖いので

**Comment by yuji** [comment]
@cheebow #185 でも書きましたが、Markdown なものは Markdown。ソレ以外はHTMLエディタかなと。

**Comment by cheebow** [comment]
@yuji であれば、今の実装で問題ないってことですかね？

**Comment by yuji** [comment]
@cheebow そうですね。既存の記事を編集するときにエディタが適切になってて、表示するようになるから、設定の方でエディタの設定をゴニョゴニョも出来なくていいですね。M -> H とか H > M とか変更することもないだろうし。

**Comment by yuji** [comment]
@cmatsuo とうことで、エディタ上で上でモードを表記する＋エディタを途中で変えるというユースケースも薄そうなので、現状ママかなと。
