### ISSUE TITLE
Markdown format editor screen always should be displayed like Markdown format editor

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#185]
Relate to #172

Steps:
1. Create an entry which created with Markdown format, send it to MT.
2. Go to Entries.
3. Select the entry you created at step 1.
4. Open Edit Body screen.

Expected: Markdown editor screen. (I mean, you can find "Marckdown" on the Editor.)
Observed: editor with a camera icon. (see attached image)

![md](https://cloud.githubusercontent.com/assets/546386/12842235/c8a4495c-cc34-11e5-8250-80650814b6d0.jpg)

**Comment by cheebow** [comment]
@yuji @oguraayumi 今、新規のブロックエディタでは、カメラアイコンのところにHTMLとかMarkdownとか表示してるんですけど、再編集時はどうしましょう？
というか、HTMLかMarkdownかをどう表示するか(アイコンにするとかも含めて)考えたいなと思います。

**Comment by yuji** [comment]
@cheebow @oguraayumi 再編集というのは、MTのの記事を編集するときですかね？

**Comment by cheebow** [comment]
@yuji CMS側に保存してある記事の再編集時です

**Comment by yuji** [comment]
@cheebow @oguraayumi 記事の編集時も Markdown は Markdown なエディタで、それ以外は HTMLエディタというふうにしてあげたいので、何かしら表示は必要してあげないと、これどっちだ？というのがわからないので、識別する何かは出したいですね。

**Comment by yuji** [comment]
@oguraayumi この辺、UIとして何か手ありますかね

**Comment by oguraayumi** [comment]
![portrait - 15](https://cloud.githubusercontent.com/assets/618638/12935469/4a17f4dc-cfd9-11e5-8ca8-2cf4c4b07fb9.jpg)
![portrait - 16](https://cloud.githubusercontent.com/assets/618638/12935468/4a0da7f2-cfd9-11e5-9086-6d0d51339e1f.jpg)

それぞれ現在の編集モードをアイコン化してみました。
ツールバーからマークダウン表記やHTML表記のサポートを表示しますか？（理解できておらず、
すいません）であれば、アイコンを別の場所に移動する必要があるとおもいます。
@yuji @cheebow

**Comment by yuji** [comment]
@oguraayumi おお、よさげ。
@cheebow これなら カメラアイコンとモード表示を両立して配置しておいておけますかね

**Comment by cheebow** [comment]
@yuji @oguraayumi  ですね。できれば、画像のサイズを統一してもらえるとうれしいです

**Comment by oguraayumi** [comment]
https://drive.google.com/open?id=0B3DAAwwej82XeU1ldUNlT2xmY28
こちらに画像をupしました。
zeplin
https://app.zeplin.io/project.html#pid=56a70f84c53ee8e71c6043f7&sid=56baf1eabef30a257998f4f5
https://app.zeplin.io/project.html#pid=56a70f84c53ee8e71c6043f7&sid=56baf1f56498ba9d0beb01a5
@cheebow

**Comment by cheebow** [comment]
実装しました。

@oguraayumi カメラアイコンとの間隔はシステムに任せるとこんな感じです。調整する場合は、画像の左に余白をつける必要がありそうです。

**Comment by yuji** [comment]
@cmatsuo build 77

**Comment by cmatsuo** [comment]
verified implements.
