### ISSUE TITLE
When editor format set was "Plain" it should be also "Plain" on CMS

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#190]
Steps:
1. Go to Create an entry > Settings
2. Change editor format setting to "Plain", save change.
3. Go to Edit Body screen.
4. Make sure you see HTML icon on the editor, input something, save it.
5. Send the entry to MT.
6. On CMS, open that entry, see body editor format.

Expected: "None".
Observed: "Rich Text".

FYI: If you set "Markdown" or "Rich Text" at step 2, you'll find the same format setting at step 6.

**Comment by cheebow** [comment]
修正しました

**Comment by yuji** [comment]
@build 78

**Comment by cmatsuo** [comment]
verified fix.
