### ISSUE TITLE
Unable to preview an entry/page

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#191]
steps:
1. Go to Create entry.
2. Input something to title, fields...
3. Tap eye icon on footer for preview entry. 

Expected: Preview entry.
Observed: Preview screen doesn't display anthing (see attached image)

FYI: On Edit Body scree, you can preview body. You just can't preview whole entry preview.
FYI 2: This isn't dupe of #169. I can't preview entry on an environment where I could see uploaded assets. 

![preview](https://cloud.githubusercontent.com/assets/546386/13000277/e12e99f2-d19b-11e5-8a31-27ff6f31c86e.jpg)

**Comment by cheebow** [comment]
@cmatsuo こちら再現しないのですが、再現させる方法はありますか？

**Comment by cmatsuo** [comment]
やはり #169 のdupeかも。#169の検証待ち

**Comment by cmatsuo** [comment]
その後の現象についてNotes:
* MT上に既存の画像をアップロードすると、リネーム後、app上では表示されなくなった
* 記事の作成時には表示されていたアップロード画像が、MT送信後の編集画面では表示されない（aws環境。アイテム一覧等でも画像は全く表示されていない 20160301）

**Comment by cmatsuo** [comment]
証明書の入ったmtqa4できちんと表示できることを確認。
