### ISSUE TITLE
Display file_name instead of "Image" on Uploader

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#192]
@yuji What do you think?

![uploader](https://cloud.githubusercontent.com/assets/546386/13002887/51a6e8ba-d1b5-11e5-9319-4a85daf65b22.jpg)

**Comment by cmatsuo** [comment]
relate to #116

**Comment by yuji** [comment]
@cheebow 写真 じゃなくファイル名にできますか？

**Comment by cheebow** [comment]
@yuji  ファイル名にすると、全部同じ時間に表示してしまうので、ファイル名が同じになってしまうんです。デザインは暫定的なものなので、そもそも文字を表示しないってのもありかと思います。
もしくは、投稿できたときにファイル名は決定できるので、そのタイミングで表示するかですね

**Comment by yuji** [comment]
@cheebow アップロードファイル名ってアップロード時にオリジナルのものに変えていると思いますけど、それをこのタイミングで出すのは大変な感じですか？

https://github.com/movabletype/smartphone-app/wiki/v1_0_0#%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E5%90%8D

@oguraayumi それか、サムネイルとプログレスバーだけのほうがすっきりですかね？

**Comment by yuji** [comment]
ああ、ちがうｗ　ファイル名についてはかいてあったw

**Comment by yuji** [comment]
ということで、

@oguraayumi さん。アップロードのところですけど、サムネイルとプログレスバーだけのほうがすっきりですかね？

**Comment by cheebow** [comment]
@yuji あ！ファイル名、撮影日ではなくて、POSTした時間だと勘違いしていました！撮影日にすれば解決するかも。
で、ここで画像って出したのはこの同じUIで最後にエントリの投稿もつけると、オフライン対応もできるかなと思って、出していたというのがあります。UIについては考えたほうがいいかもですね。

**Comment by yuji** [comment]
@cheebow おっと、もしかしてこれまでもファイル名はPOST日時でしたかｗ

UIについてはなるほど。
@oguraayumi さん、@cheebow さんとちょっとアイディアひねり出しますか。

**Comment by cmatsuo** [comment]
@yuji  すいません。再確認ですが、撮影日時がファイル名としてアップロードされる。でOK?

**Comment by oguraayumi** [comment]
![uploading](https://cloud.githubusercontent.com/assets/618638/13098553/8a8ae012-d56d-11e5-9970-429b229455c1.png)

・ファイル名を撮影日時にしました。
・記事もuploadされるということなので、imageと区別がつくように頭にアイコンをいれてみました。
・写真のある記事の場合は先頭の写真を、写真がない記事の場合はnoimageのグレーのバッテンつきのサムネイルをつくってみました。

@yuji @cheebow @cmatsuo

**Comment by yuji** [comment]
@cheebow ファイル名ですけど、v1.0のときと仕様変えてないはずなので mt- ががつくかなとも。

https://github.com/movabletype/smartphone-app/wiki/v1_0_0#%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E5%90%8D

あと v1.0 のときに確認していなかったので申し訳ないのですが・・・。外部からiPhoneに入れられた写真とかって、撮影日時ってどうなります？

**Comment by yuji** [comment]
撮影日時が取れなかった時は現在日時とする。

**Comment by yuji** [comment]
@oguraayumi 
* 記事と写真のセットは一つまで
* 画像しか無いパターンもあり
* 記事にはサムネイルじゃなく記事用のアイコン的なもの

**Comment by oguraayumi** [comment]
![uploading](https://cloud.githubusercontent.com/assets/618638/13135926/4538a86e-d658-11e5-8ff8-fc532e3d5cbb.png)

修正しました。ご確認くださいませ。
@yuji @cheebow

**Comment by yuji** [comment]
@cheebow おねがいしますー

**Comment by cheebow** [comment]
@oguraayumi デザイン仕様と画像をお願いします

**Comment by oguraayumi** [comment]
お待たせしてもうしわけありません。
仕様はこちらです。
https://zpl.io/ZEjLU5

画像はこちらです。
https://drive.google.com/open?id=0B3DAAwwej82XeU1ldUNlT2xmY28

@cheebow @yuji

**Comment by cheebow** [comment]
実装しました

**Comment by yuji** [comment]
@cmatsuo build 89

**Comment by cmatsuo** [comment]
Verified implements.
