### ISSUE TITLE
It's better if the app could somehow let user know image file upload limit is 8

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#193]
When you upload multiple images, the limit is 8 but the app doesn't say about it. It's just you can select images 'till 8.

I'm not sure how, but it's better if the app let user know somewhere , somehow. Need idea for UI.

**Comment by cmatsuo** [comment]
relate to #116

**Comment by yuji** [comment]
@cheebow 9枚目を選んだ時点で 8枚までですよ。ってメッセージをポップアップしてあげる。とかできますかね？

**Comment by cheebow** [comment]
@yuji そもそも9枚目が選択できないようになっています。枚数の制限をつけないこともできます。

**Comment by yuji** [comment]
@oguraayumi @cheebow 選べないだけだと、押してんのになんで！？ってなるかなあとも思いまして。制限なしにすると大変なことが（主にサーバー側）おきそうなので、8枚制限はいいかなと。

**Comment by cheebow** [comment]
@yuji このライブラリだと9枚目を選択したときにアラートを表示するというのは難しそうです。文字が入るかどうか不安ですが、ナビゲーションバーのタイトルに書いておくってのはありかもしれません。

**Comment by yuji** [comment]
@cheebow なるほど。木曜に話しましょう

**Comment by yuji** [comment]
9枚目が選ばれた時にアラートを出す方向で。

**Comment by cheebow** [comment]
@yuji アラートの文言どうしましょう？

**Comment by yuji** [comment]
@cheebow かんがえまーす

**Comment by yuji** [comment]
@cheebow 

You can upload 8 photos at once.
一度にアップロードできるのは8枚までです。

ですかね

**Comment by cheebow** [comment]
実装しました

**Comment by cmatsuo** [comment]
verified implement!
