### ISSUE TITLE
Unable to upload asset by "Take a photo"

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#201]
I'm testing on aws.
Since I updated to #79, I have this problem.

Steps:
1. Go to Assets > Photos > Take a photo.
2. Take a photo and tap Use Photo.

Expected: Upload the photo.
Observed: Back to Photos screen and Nothing happen.

FYI: You can upload photos by "Select from..". Also, same thing's happen when you try to insert photo to entry/page.

**Comment by cheebow** [comment]
こちらでは再現できないのですが、もしかするとというところがあったので、そこを修正してみました

**Comment by yuji** [comment]
build 80

**Comment by cmatsuo** [comment]
なんと、その「もしかすると」で直ってしまいました。
