### ISSUE TITLE
Unable to set custom image size value

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#202]
Steps:
1. Go to blog dashboard > Settings > Image Size.
2. Set custom size value, tap "Done".

Expected: Set custom image size value.
Observed: Please enter a custom size. 

FYI: If you select other sizes, you can set the size.

![unknown](https://cloud.githubusercontent.com/assets/546386/13168431/ed72f94a-d71f-11e5-809c-34eda65ef232.jpg)

**Comment by cheebow** [comment]
すみません！！　エンバグしてました。
修正しました

**Comment by yuji** [comment]
build 81

**Comment by cmatsuo** [comment]
修正を確認。そして、貼り付けた画像が間違ってましたね。すみませんｗ
