### ISSUE TITLE
アップロード先での相対パスの指定を、設定保存時点でエラー通知を出して欲しい。

### ISSUE THREAD

**Issue by ikoaoki** [movabletype/smartphone-app#203]
重要度は余り高くなくリクエストベースです。

MTiOSのブログの「設定」でアップロード先を指定出来ますが、そこで「../iPhone」などのように相対パスでの入力も問題なく保存できます。

![mt-20160219182125](https://cloud.githubusercontent.com/assets/6724607/13171445/4983e396-d736-11e5-94e0-92e9848cb660.jpg)

が、実際にアイテムアップロード時には、「追加パスが不正です」と出ます。

![mt-20160219181843](https://cloud.githubusercontent.com/assets/6724607/13171471/768d661e-d736-11e5-980a-f9e856b00e3a.jpg)

「設定」段階で相対パスでの入力を検知したら、せめて設定保存時に「追加パスが不正です」と通知を出しておくのは、いかがでしょうか。

CMS側では、「有効なパス名を指定してください。」といった通知が出るので、それと同じような動きを期待してのことです。

アップロード先を、%s、などのformatでの指定が実装出来るようになると、こういった相対パスでの指定を試みる人も出てきそうに思いますので…。

**Comment by yuji** [comment]
アップロードパスの件とは別に、. .. など相対パス指定はinput validation のエラーとしましょう

**Comment by cheebow** [comment]
修正しました

**Comment by yuji** [comment]
build 82

**Comment by ikoaoki** [comment]
@yuji @cheebow 

ビルド82で確認しました。

#### 相対パス /../ でエラー通知を確認。
確かに、/../iPhone のように、相対パス　../　で　設定保存しようとすると、エラー通知が出るのを確認しました。


ですが、もう少し意地悪すると…。


#### アプリ側で、アップロード先に、/..iPhone/ と、した場合

* アップロード先として、指定できる。
* だが、実際に画像をアップロードすると、「追加パスが不正です」と出る。

#### CMS側で、アップロード先に、/..iPhone/ と、した場合

* 全般設定で、アップロード先を保存時点で、「有効なパスを指定してください。」と出る。


-----

細かいですが、CMS側と同じく、「..」と連続するピリオドで、バリデーションチェックするように、合わせることを希望します。

**Comment by cheebow** [comment]
@yuji 今、「./」を含んでいるかどうかでチェックしているんですが「./」か「..」を含んでいたらとしたほうが良いですかね？　CMSの方ではどういうロジックを使っていますか？

**Comment by ikoaoki** [comment]
（因みに、CMS側では、「/.iPhone/」は使えることを確認しています。）

**Comment by yuji** [comment]
@cheebow MTのJSでは

function is_valid_path(path_){
    var str = path_.replace(/[ "%<>\[\\\]\^`{\|}~$\+,\/:;=\?@]/g, "");                              
    str = encodeURIComponent(str);                                                                  
    if (str.indexOf('%') != -1) {                                                                   
        return false;                                                                               
    }                                                                                               
    if (str.match(/\.\./)) {                                                                        
        return false;                                                                               
    }                                                                                               
    return true;                                                                                    
}                                                                                                   

こうですね。％入ってたらnon-asciiだろう。..はダメよ。というチェック。

**Comment by cheebow** [comment]
修正しました

**Comment by yuji** [comment]
build 83

**Comment by ikoaoki** [comment]
ビルド83にて、確認いたしました。

* ブログの全般設定からの、「アップロード先」の指定で、「..」を含んでいるとエラー通知
* アイテムアップロード時の、「アップロード先」の指定で、「..」を含んでいるとエラー通知

上記、確認できましたので、こちらcloseいたします！
細かい指摘に対応有難うございました！
