### ISSUE TITLE
Auto-renamed asset file name run over the screen

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#204]
Steps:
1. Upload a image to the app.
2. Upload same image to same path.
3. The app rename file name automatically and... look at attached image.

Renamed file name is always "40 digit + .jpg" , and the screen size cannot display last 3 letters.
@oguraayumi What do you think? Can you display all 44 digit in the screen somehow? 

![namae](https://cloud.githubusercontent.com/assets/546386/13171520/9ef9f086-d736-11e5-996e-06d789862649.jpg)

**Comment by oguraayumi** [comment]
サムネイルとテキストの間隔をせばめて、
3行で最大文字数がおさまるようにしてみました。
幅の狭い端末でも3行でおさまります。
https://zpl.io/Z1BzkDK
@cmatsuo @yuji @cheebow

**Comment by cheebow** [comment]
修正しました

**Comment by yuji** [comment]
build 88

**Comment by cmatsuo** [comment]
確認しました。ばっちりです。
