### ISSUE TITLE
Limit custom image size number of letters

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#207]
You can save "999999999999999999" as Custom image size but you don't need to save that huge value, right? 
How about cap the form input availability limit to 4 digits or so?

Btw, I tried to upload with 9999 px setting (uploaded image size is 2448 × 3264 px), and the app has got shut down. I also tried 9000 and I could upload the image without hitch. 
Shut down isn't good behavior...but, um, maybe we should set limit value for the form or something?

![limit](https://cloud.githubusercontent.com/assets/546386/13208435/3c4bf86c-d95c-11e5-8652-83ebce7eaea8.jpg)

**Comment by cmatsuo** [comment]
relate to #164

**Comment by yuji** [comment]
@cheebow 9999 くらいを目処に入力上限を設けようと思うんですけど、いくつくらいがいいんでしょう

**Comment by cheebow** [comment]
@yuji 9999あれば十分な気がします

**Comment by cmatsuo** [comment]
@yuji @cheebow 上にも書きましたが、9999を設定して、アセットのアップロード画面からアップロードすると、アプリがフリーズの後落ちるですよ

**Comment by cheebow** [comment]
@yuji @cmatsuo おそらく、画像が大きすぎてメモリが足りないのではないかと。オリジナルより大きいサイズにはできないようにしても良いのかもしれません。
メモリに関しては、機種や状況によって変わってきてしまうと思います。

**Comment by cmatsuo** [comment]
＞オリジナルより大きいサイズにはできないようにしても良いのかもしれません。

@cheebow @yuji 
CMSの画像編集画面でも、オリジナルより大きいサイズにはできないので、それが仕様としてわかりやすいかも

**Comment by cheebow** [comment]
@cmatsuo 設定では上限を8000(8K)までにして、リサイズ時には画像サイズより大きくなるようにはしないってのがよいかなと。

**Comment by cmatsuo** [comment]
+1 @cheebow 案

**Comment by yuji** [comment]
@cheebow それでいきましょう。

**Comment by yuji** [comment]
Wikiにも追記
https://github.com/movabletype/smartphone-app/wiki/v1_1_0#image-width-164

**Comment by cheebow** [comment]
修正しました

**Comment by cmatsuo** [comment]
* カスタム値は上限8000であることを確認
* 画像widthがカスタム値より小さい場合、アップロードした画像widthはオリジナルサイズを利用することを確認
