### ISSUE TITLE
本文のブロック入力後のHTMLソースがアプリ側とCMS側で異なっている。かつもう少し整えて欲しい。

### ISSUE THREAD

**Issue by ikoaoki** [movabletype/smartphone-app#208]
この辺りは既に検討事項になってるかもしれませんが。

#### 現象
フォーマット「リッチテキスト」＋ブロックエディタ　入力で出力されるHTMLソースが、アプリ側とCMS側で異なっているものが表示される。

#### 手順
1) アプリ側で、新規記事作成で、エディタ「リッチテキスト」を選択する。
2) ブロックエディタで、本文に改行を含む文字を入力する。

![mt-20160222113456](https://cloud.githubusercontent.com/assets/6724607/13208376/77a4f0d6-d95b-11e5-8b4b-b0c126c8b49d.jpg)

3) 「保存」＞「送信する」でアプリ側に記事を送信する。
4) ＜アプリ側＞から「記事の一覧」から、2)で書いた記事を開く。

HTMLソースは以下のようになっている。
![mt-20160222113823](https://cloud.githubusercontent.com/assets/6724607/13208396/aed1f004-d95b-11e5-83c6-feec82ff89af.jpg)

5) ＜CMS側から＞「記事の一覧」から、2)で書いた記事を開く。
　　「本文」をHTMLモードで見る。

<img width="615" alt="2016-02-22 12 00 39" src="https://cloud.githubusercontent.com/assets/6724607/13208412/ec3b458a-d95b-11e5-998b-a8cf04aa5f51.png">

#### 結果
6) アプリ側とCMS側で、pタグのまとめ方などが明らかに違う。
　（brタグはアプリ側では表示しない、などの傾向はわかるのですが）

#### 要望

アプリ側とCMS側で表示されるHTMLソースを揃えて欲しい。
かつ、改行するとdivタグで囲まれる、など違和感があります。

ブロックエディタ入力　＝　段落（p）入力、　とコツが分かれば、と改行divタグの件はByDesignではあると思いますが。

個人的に自サイトに、アプリ経由で投稿した際、出てきた本文のHTMLソースに、ひぃ！となり、いちいち手入力で修正する、ということをやったので…（ソース厨という程ではありませんが）

**Comment by yuji** [comment]
個人的には、HTMLを気にするのであれば リッチエディタは使うべきではない。と思っています。

**Comment by ikoaoki** [comment]
> HTMLを気にするのであれば リッチエディタは使うべきではない

確かに…。
個人でやる際は自身はMarkdown使うことが多いのですが、ただ、アプリのデフォルトはどうしてもリッチテキストになっていますし、一般ユーザーだと、リッチエディタの利用が多くなるのでは、と思います。

最近はスマホからの入力は「基本テキストのみ」が多いですし（彩りはLINEのスタンプ）、いっそ、デフォルトが「改行を変換」or「プレーンテキスト」にするのは…乱暴かな。

**Comment by ikoaoki** [comment]
うーん、、やはり、リッチテキストエディタだと、
「ただの改行」で打った文章なのに、
最初の一行だけが、`` <p> ``タグで、囲まれて、
その下の行は、`` <div> ``タグで囲まれていく… ので、

いっさい文字装飾もせず、ただ改行してるだけの文章が、スマホからCMSにPublishで送信すると、表示がおかしなことになるので、やはりこれは何とかして欲しい…。

![2016-02-26 14 24 07](https://cloud.githubusercontent.com/assets/6724607/13343963/e6a98e74-dc94-11e5-8f6c-1f62066c2259.png)

**Comment by yuji** [comment]
@ikoaoki 「揃える。」ということではなく、「最初の行だけPでくくられる。」ということであれば、そういったケースにしてもらえると。そして、それは要望じゃないです。明らかにおかしい現象ということでしょう。

**Comment by ikoaoki** [comment]
@yuji そうですね、ソースレベルだけの話ではありませんね…。　#221　にて報告させていただきました。

**Comment by yuji** [comment]
Thanks

**Comment by yuji** [comment]
ちょっと一旦こっちもclose
