### ISSUE TITLE
アプリ側の「アップロード先」のデフォルトを、CMS側の全般設定で設定した「アップロード先」に合わせる。

### ISSUE THREAD

**Issue by ikoaoki** [movabletype/smartphone-app#209]
リクエストベースのものばかりで申し訳ないですが。
（%sなどの指定方を検討中のようなので、そこで既に予定されているお話かもしれませんが）

#### 要望
アプリ側の「アップロード先」のデフォルトは、サイトパスになっていますが、デフォルトは、CMS側の全般設定で設定した「アップロード先」の情報を持ってくるのではどうでしょうか。

（個別に設定すれば、そちらが優先される。あくまでも「デフォルト」として）

#### 背景
CMS側では、「全般設定」でデフォルトのアップロード先が指定されますし、
CMS側とアプリ側のアップロード先が別々である必要を、そこまで強くは感じなかった為。（別にしたいならば、ユーザーが都度設定すればいいかな、と）

デフォルトが「サイトパス」になってるのも余り良いようには感じなかった、というのもあります。（サーバーの中がとっちかる…。これこそByDesignではありますが）

**Comment by yuji** [comment]
v1.1 の目玉です。

https://github.com/movabletype/smartphone-app/wiki/v1_1_0#upload-destination-173

**Comment by ikoaoki** [comment]
おおっと、失礼いたしました。
楽しみにしています。
