### ISSUE TITLE
L10N: 無効なパス名指定時の通知「You must set a vaild path.」

### ISSUE THREAD

**Issue by ikoaoki** [movabletype/smartphone-app#212]
アップロード先に、「..」などの無効なパス名を指定した時のエラー通知。
![mt-20160222171051](https://cloud.githubusercontent.com/assets/6724607/13212998/0c604608-d989-11e5-81eb-82515ebbc6b7.jpg)

CMS側では、「有効なパス名を指定してください。」となっている模様。

**Comment by yuji** [comment]
already filed. #168
