### ISSUE TITLE
入力項目「タグ」が消えている。

### ISSUE THREAD

**Issue by ikoaoki** [movabletype/smartphone-app#213]
ビルド83で発生確認しております。

記事の作成、編集画面にて「タグ」入力項目がありません。
右下からの「編集＞並び替え」にても、「タグ」の項目が消えてしまっているようです。
![mt-20160222174538](https://cloud.githubusercontent.com/assets/6724607/13213474/7b9cc994-d98c-11e5-8da4-8ece17961c5b.jpg)

いつから消えちゃったのでしょう…。
ビルド83以前から消えているかもしれませんが、83にて気づきました。

**Comment by cheebow** [comment]
@ikoaoki @yuji タグは詳細設定で入力するので、ここには表示されていないはずです。これは、最初からそういう仕様です。

**Comment by yuji** [comment]
@cheebow あ、そうだった。フィールドじゃないんだった。Wikiの方を書きなおしておいたほうがいいな・・間違う・・。

**Comment by ikoaoki** [comment]
@cheebow せきねさん

あー、失礼しました。
なるほど、左下からの「詳細設定」ですね。

すみません、並び替え項目、にてっきり入っているものかと……。

**Comment by yuji** [comment]
@ikoaoki WikiがそうなりっぱなしだったのでQAシートがもしそうなっていたらアップデートお願いします。
今しがたWikiも更新済み。ごめんなさい。
