### ISSUE TITLE
エディタにMarkdownを指定した時、CMSに送信後もMarkdown記法を維持して欲しい

### ISSUE THREAD

**Issue by ikoaoki** [movabletype/smartphone-app#216]
### 要望
エディタに「Markdown」を指定して、本文＆続き、をMarkdown記法で入力し、CMS側に送信後に、記事編集で開くと、エディタはMarkdownになっているが、本文＆続きが、HTMLに変換されて表示されるので、Markdown記法を維持して欲しい。

### 再現手順
1.  アプリ側で、「新しい記事」を開く。
2. 詳細設定で、エディタ「Markdown」を選択する。
3. 「本文＞テキスト」でMarkdown記法で入力する。
4. 「完了」を押し、記事編集画面で「保存」を押す。
5. 「送信する」を選択。（ステータスはDraftのままでよい）
6.   送信後、記事の「本文」を開く

### 結果
7） Markdown記法が選択されていることが、左下のMマークに出ているが、HTMLで本文が表示されている。

（CMS側でも、フォーマット「Markdown」となっているが、本文には、HTMLで表示されている）

### メモ
未送信の記事、状態であれば、ブロック入力も記法も維持されるのは確認していますので、未送信状態で、存分に記事を編集してから、送信しろ、ということかもしれませんが。

記事を送信後、せっかくのMarkdownが維持されないのは、違和感があります。

制限事項？ではあるかもしれませんが。Markdownが維持されるのを希望します。

![mt-20160223155930](https://cloud.githubusercontent.com/assets/6724607/13244139/4e974170-da47-11e5-9be4-d8aba8e7ac6f.jpg)
<img width="658" alt="2016-02-23 16 01 59" src="https://cloud.githubusercontent.com/assets/6724607/13244143/545fd73e-da47-11e5-965d-d514a7b327bb.png">

**Comment by yuji** [comment]
送信後にブロックエディタにならないのは仕様ですが、

https://github.com/movabletype/smartphone-app/wiki/v1_1_0#markdown-support-172

にあるように Markdown のものは Markdown のままにするのが仕様。

**Comment by cheebow** [comment]
修正しました

**Comment by yuji** [comment]
build 86

**Comment by ikoaoki** [comment]
こちら、報告した手順で、現象が解決されていることを、確認したのでcloseいたします！問題なくMarkdownが送信後もHTMLに切り替わらずに維持されていました！

ただ、確認作業の中で、#218　の現象を見つけたので、これとは別のissueとさせていただきました。
