### ISSUE TITLE
未送信のMarkdown記法の記事が、特定の手順で送信時にpタグが入ってしまう。

### ISSUE THREAD

**Issue by ikoaoki** [movabletype/smartphone-app#218]
#216 確認時に遭遇しました。
ビルド88です。

### 現象
未送信のMarkdown記法の記事が、本文の再編集で、何も変更加えないままに、＜で戻ると、送信時にpタグが入れられてしまう。

### 再現手順

1) アプリ側で、「新しい記事」を開く。
2) 詳細設定で、エディタ「Markdown」を選択する。
3) 「本文＞テキスト」でMarkdown記法で入力する。
4) 「完了」を押し、記事編集画面で「保存」を押す。
5) 「下書き保存する」を選択する。

6) 「未送信の記事」から、5の手順の記事を開く。
7) 「本文」を開いて、Markdown記法しているブロックを開く。（本文＞テキストの編集画面になっている状態）
8) 何も変更せず、　＜　で前の画面に戻る。（完了、ボタンを押さない！）
9) さらに、もう一度、＜　で前の画面に戻る。（完了、ボタンを押さない！）

10) ここで、「ナビゲーションの確認」が出るが「OK」を押す。
![mt-20160225152949](https://cloud.githubusercontent.com/assets/6724607/13311918/be579200-dbd5-11e5-8683-d5d658f9012d.jpg)

11) 「保存」を押して、「送信する」を選ぶ。

12) 送信完了後の画面で、「本文」を開く

### 結果
13) Markdown記法のテキストが、p　タグで囲まれてしまっている。
![mt-20160225153438](https://cloud.githubusercontent.com/assets/6724607/13311920/c32653de-dbd5-11e5-94ad-daf5063173da.jpg)

### メモ
「ナビゲーションの確認」で、＜保存されていない変更は失われます。移動してもよろしいですか？＞と出ているのですが、

作業者としては、「本文＞テキスト」を開いただけで、変更作業は一切何も手を加えていないので、「保存されていない変更」がある訳がない、と躊躇なく、OKボタンを押してしまいます。

未送信の記事状態で、本文＞テキスト　を開いただけで、変更が加わってしまい、そこに、段落のpタグで囲まれてしまうのは、かなり不便に思います。

未送信記事を、送信前に、「一応開いて中身を確認する」という動作は、ごく自然にあり得るんじゃないかな、…と。（　手を加えていないなら、＜　の戻る　を使うのもごく自然な動作かと）

**Comment by cheebow** [comment]
@yuji @ikoaoki 
送信時にブロック項目にpタグをつけて送信しているためだと思います。
pタグは必要ないですか？
でも、ブロックごとに分けておきたいですよね。

**Comment by ikoaoki** [comment]
ううん…。ブロックエディタで、ブロック毎にpで段落化されるのはいいのですが、
Markdown記法しているのに、pタグで囲まれてしまうと、サイトで、

## 見出しだ - リストリスト - リスト

と表示されてしまって、Markdownが全く機能して表示されなくなってしまいます。
Markdownの時は、なんとかほにゃらら出来ないものでしょうか。

**Comment by yuji** [comment]
@cheebow Markdownである場合は、P無しでOKな気がします。Markdown のときは 1段落というよりもっと情報量多そう。

**Comment by cheebow** [comment]
修正しました

**Comment by yuji** [comment]
build 91

**Comment by cmatsuo** [comment]
#218 の修正ですでに修正済みだったんじゃないかと思いますが、#218 の修正によって現状再現の仕様もないので、クローズします。
