### ISSUE TITLE
リッチテキストエディタで改行のみのテキストを、CMSに送信すると、最初の一行だけが p タグで囲まれて段落化されている。

### ISSUE THREAD

**Issue by ikoaoki** [movabletype/smartphone-app#221]
関連　#208
ビルド88　にて確認。

### 現象
アプリで、「リッチテキストエディタ」で、改行のみのテキストを、CMSに送信すると、最初の一行だけが、p タグで囲まれて段落化され、他の行は div タグで囲まれている。

### 再現方法

1) アプリで、「リッチテキストエディタ」で新しい記事を作成する。
2) 本文＞テキスト、　で、改行のみの文章を入力する。

![mt-20160226144025](https://cloud.githubusercontent.com/assets/6724607/13344331/5c14f7c2-dc98-11e5-9954-d97f241abac4.jpg)

3) 完了、ボタンを押す。
4) ステータスPublish　で、保存、ボタンで、「送信する」を選択する。

### 結果

ただの改行のみの文章が、以下のように表示されている。
![2016-02-26 14 48 29](https://cloud.githubusercontent.com/assets/6724607/13344294/0b55b7d6-dc98-11e5-8281-ddbd2365591c.png)

### この結果でのCMS上でのソース表示
<img width="462" alt="2016-02-26 14 51 47" src="https://cloud.githubusercontent.com/assets/6724607/13344355/7d6fe418-dc98-11e5-90f6-83b89a65010e.png">

このように、一行目のみが、p　タグで囲まれている。
これは、ただの改行のはずが、一行目だけが段落表示になっており、ユーザーとしては、かなり意図しない表示になると思われます。

**Comment by yuji** [comment]
@cheebow #218 と似たような話な気がしますが、最初の行だけっていうのが気になるかも

**Comment by cheebow** [comment]
@yuji たしか以前にも話題になった気がするのですが、このアプリで使っているWISYWIGエディタの仕様だった気がします。

**Comment by cheebow** [comment]
@yuji 
アプリからは

```
<p>Fsdfdsfdsfds
<div>Fsdfdsfdsfds</div>
<div>Fsdfdsfdsfds</div>
<div>Fsdfdsfdsfds</div>
<div>Fsdfdsfdsfds</div>
<div>
    <br />
</div></p>

```

これが送られているようです。
CMS側で変わっている気もしてきました

**Comment by cheebow** [comment]
このpタグはブロックの区切りとして僕が付与しているものです。

**Comment by yuji** [comment]
@cheebow たしかになんかそんな話した記憶ありますね。この<p>を取り除くと、アプリ的に厳しい感じですか？

**Comment by cheebow** [comment]
@yuji ブロックの区切りいらないですかね？

**Comment by yuji** [comment]
@cheebow アプリ的になくてもダイジョウブであれば取ってしまいましょうか。思いの外、ブロックは結構デカそう。<div>のほうがいいかもしれないけど、<div>でやると事故起きそう。

**Comment by ikoaoki** [comment]
（成る程……このエディタの性質か…。CMS側でいうフォーマット「改行を変換」が欲しい）

**Comment by cheebow** [comment]
@yuji 
アプリ的には問題ないんですが、テキストのブロックが連続した場合、表示上くっついちゃいませんか？

**Comment by yuji** [comment]
ちょっと一回整理しましょうか。よくよく読むと @cheebow さんの言っていることと @ikoaoki さんの言っている事象に若干のズレがある。

@ikoaoki 
MT側のフォーマットをなしにしてみて、アプリから手順通りのことをしてみてください。

**Comment by cheebow** [comment]
@yuji 
アプリから

```
<p>Fsdfdsfdsfds
<div>Fsdfdsfdsfds</div>
<div>Fsdfdsfdsfds</div>
<div>Fsdfdsfdsfds</div>
<div>Fsdfdsfdsfds</div>
<div>
    <br />
</div></p>

```

これを送り、CMS側のエディタをリッチテキストからなしにすると

```
<p>Fsdfdsfdsfds</p>
<div>Fsdfdsfdsfds</div>
<div>Fsdfdsfdsfds</div>
<div>Fsdfdsfdsfds</div>
<div>Fsdfdsfdsfds</div>
<div></div>

```

このHTMLが現れる感じです。
CMS側のリッチテキストエディタが、変換してるという印象

**Comment by cheebow** [comment]
@yuji 
Pタグをつけずに

```
Aaaaa
<div>Bbbbb</div>
<div>Ccccc</div>
<div>
    <br />
</div>
```

これを送ると

```
<p>Aaaaa</p>
<div>Bbbbb</div>
<div>Ccccc</div>
<div></div>
```

こうなりました

**Comment by yuji** [comment]
MTなにしてんだ・・・
とりあえず、状況としてはMTが悪い。ということになりそうなので
区切りのPもそのままにしましょう。

@ikoaoki MTか、DataAPIか不明だけど、関根さんの書いた感じになるよ。っていうケースをFogBugz
にお願いします。

**Comment by ikoaoki** [comment]
@yuji 高山さん

了解です。今、TinyMCEを無効にして試したら、TinyMCEの時とはまた違うソースが…（CKEditorでの表示）。それらも合わせて、FogBugzに報告いたします。

**Comment by yuji** [comment]
ん？CKEditorってどういうことです？

**Comment by ikoaoki** [comment]
@yuji あれ、TinyMCEプラグインを無効にすると、出てきてるエディタは、CKEditorではないのでしたっけ。記事作成画面で、以下のようなエディタが出てくるのですが。
<img width="671" alt="2016-02-26 17 15 07" src="https://cloud.githubusercontent.com/assets/6724607/13346828/83b2c6d8-dcac-11e5-8c8f-332ebc3675fd.png">

（すみません、勘違いしてるか…？）

**Comment by yuji** [comment]
CKEditor は一度も搭載したことないですね。ArchType Editor と呼ばれていた Six Apart 謹製のエディタです。

**Comment by ikoaoki** [comment]
> Six Apart 謹製のエディタ
ひー！すみません……ずっとずっとCKEditorだと思ってました…。（歴史を知った）

**Comment by ikoaoki** [comment]
FogBugz に以下のように報告をいたしました。
https://movabletype.fogbugz.com/f/cases/113811/MTiOS-MT

**Comment by yuji** [comment]
@ikoaoki こちらのケースはとじましょう

**Comment by ikoaoki** [comment]
了解です！
こちらのケースは、これにてcloseいたします。
