### ISSUE TITLE
Previewing entry upload entry and you get error

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#225]
Relate to #163

Steps:
1. Go to Create and Entry.
2. Input title and click Done.
3. Back to New Entry screen, click Preview icon.

Expected: Preview entry.
Observed: App starts upload and you get error.

![uploaderror](https://cloud.githubusercontent.com/assets/546386/13347195/7cc2f82c-dcaf-11e5-9283-fdd6c3234bcb.jpg)

**Comment by cmatsuo** [comment]
Possibly, this might be not happen on build #90.

**Comment by cmatsuo** [comment]
Nope. I've seeing same error.

**Comment by cmatsuo** [comment]
@yuji 
FYI: It seems this issue depends on theme of website/blog.
You get alert with:  Professional Blog, Classic Website, Classic Blog, Pico, Community Blog
You get preview without alert with: Professional Website, Eiger, rainier, Community Forum

Also, you never get the alert with Webpage preview, except Forum theme. (it doesn't have Webpage archive)

**Comment by yuji** [comment]
テンプレート「記事」の再構築中にエラーが発生しました: <mtInclude>タグでエラーがありました: モジュール「サイドバー」でエラーが発生しました: テンプレート「サイドバー」の再構築中にエラーが発生しました: <mtIf>タグでエラーがありました: <mtWidgetSet>タグでエラーがありました: ウィジェット「About」でエラーが発生しました: テンプレート「About」の再構築中にエラーが発生しました: <mtunless>タグでエラーがありました: <mtIf>タグでエラーがありました: <mtEntryDate>タグでエラーがありました: MTEntryDateを日付コンテキストの外部で利用しようとしました。

こんなエラーが出ていた。

**Comment by yuji** [comment]
$entry->authored_on には正しく値がセットされているが、preview が求めているのは authored_on_date, authored_on_time だった・・・。DataAPI側のバグと判明。

**Comment by yuji** [comment]
API 側の対応を待つ。

**Comment by cmatsuo** [comment]
@yuji 了解

**Comment by yuji** [comment]
https://movabletype.fogbugz.com/f/cases/113839

**Comment by yuji** [comment]
Marked as Known Issue in this version.

**Comment by yuji** [comment]
Fixed in https://movabletype.fogbugz.com/f/cases/113839/
