### ISSUE TITLE
Default Editor Format setting works only for Entry

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#228]
@yuji 
It also should work for Page editor as well as on CMS, shouldn't it? 

Steps:
1. Go to a blog/website > Settings.
2. Set Markdown for Editor.
3. Open Create New Page.

Expected: Find Markdown editor.
Observed: Find Richtext editor.

**Comment by cheebow** [comment]
@cmatsuo @yuji 
これ、僕のミスです。修正します！

**Comment by cheebow** [comment]
修正しました

**Comment by yuji** [comment]
build number あげ忘れた・・・DeployGate:92

**Comment by cmatsuo** [comment]
Verified fix.
