### ISSUE TITLE
Uploader: Untitled Entry/Page

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#229]
When you upload untitled Entry/Page, Uploader screen displays it like Entry/Page. 
Change it to Untitled Entry(Page) or something like that.

![untitles](https://cloud.githubusercontent.com/assets/546386/13384270/59e352d2-ded7-11e5-9f53-ae9750eb16a2.jpg)

**Comment by yuji** [comment]
Use "Untitled entry" | "Untitled page" when entry/page has not title.

**Comment by cheebow** [comment]
修正しました

**Comment by yuji** [comment]
build number あげ忘れた・・・DeployGate:92

**Comment by cmatsuo** [comment]
verified fix.
