### ISSUE TITLE
With required Image CF, you cannot create an entry/page 

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#230]
Steps:
1. Create a required *Image* custom field for entry.
2. Go to Create Entry on app.
3. Upload an image for the CF.
4. Click "Save" of header.

Expected: Save new entry.
Observed: Get error. See attached image.

![requiredcf](https://cloud.githubusercontent.com/assets/546386/13385974/7e71a01e-deea-11e5-92e3-669a9e3700a1.jpg)

**Comment by cheebow** [comment]
修正しました

**Comment by yuji** [comment]
build 94

**Comment by cmatsuo** [comment]
verified fix.
