### ISSUE TITLE
アップローダーが途中で止まったときの文言

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#231]
"There is the rest of the items , you sure that you want to upload again?"

カンマの位置が変？
"...items , you sure...?"

**Comment by yuji** [comment]
@cheebow There is the rest of the items. Are you sure you want to upload again?

こんなのでどうでしょう？

**Comment by cheebow** [comment]
修正しました

**Comment by yuji** [comment]
build 94

**Comment by cmatsuo** [comment]
verified fix.
