### ISSUE TITLE
If you Insert Image Bloc above Text Bloc, Markdown doesn't work

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#232]
Steps:
1. Go to Create New entry.
2. Go to Settings, set Markdown for Editor, save change.
3. Go to Edit Body screen.
4. Open Image bloc, insert image.
5. Open Text bloc, input something by Markdown form. For example, like this:
```
1. test
1. test2
1. test3
```
6. Send the entry to MT with publish status.
7. View published entry.

Expected: Find numbered list 1 to 3 by Markdown form under image.
Observed: Find not markdown formatted list under image. 

FYI: You need clear line before the Markdown formatted list, if you wanted the effect. I mean, Image bloc and text bloc input html like this:
```
<img alt="example.jpg" src="https://YourMovableType.jp/example.jpg" width=500 height=667 class="mt-image-none" style="" />
1. test
1. test2
1. test3
```
If you want to make it Markdown Formatted, it should be like this:
```
<img alt="example.jpg" src="https://YourMovableType.jp/example.jpg" width=500 height=667 class="mt-image-none" style="" />

1. test
1. test2
1. test3
```

**Comment by yuji** [comment]
@cheebow ブロックとブロックをつなぐときに、\n\n と改行2つ分でつなぐといいのかしら。と思うのですが、どうでしょう？

**Comment by cheebow** [comment]
@yuji やってみます！

**Comment by cheebow** [comment]
実装しました

**Comment by yuji** [comment]
build 95

**Comment by cmatsuo** [comment]
@cheebow  Fixed for "Body", not for "Extended".

**Comment by cheebow** [comment]
@cmatsuo ありがとうございます。僕のミスでした。これ、よく見つけてくださいました！
修正します

**Comment by cheebow** [comment]
修正しました

**Comment by yuji** [comment]
build 96

**Comment by cmatsuo** [comment]
verified fix!
