### ISSUE TITLE
Delete Page/Entry you just created doesn't behave like delete older Entry/Page

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#233]
Steps:
1. Go to Manage Entries, select an entry.
2. Tap Settings of footer for the entry, tap "Delete this Ennry".

Expected: App delete the entry and move to previous screen (Manage Entries in here)  automatically. And it works as you expected. 

3. Create New Entry, send the entry to MT.
4. Tap Settings of footer for the entry, tap "Delete this Ennry".

Expected: App delete the entry and move to previous screen (Website/Blog dashboard or Manage Entries) automatically.
Observed: App delete the entry but still display the Edit Entry screen. 

FYI: If you try to "Save" or "Delete this Entry" after step 4, you just get error, because it's already deleted. All you can do is close the edit entry screen and back to Dashboard.

**Comment by yuji** [comment]
作成直後は、記事一覧を経由していないですけど、記事一覧に戻ることは出来ますか？ダメそうならサイトトップでも大丈夫です。

**Comment by cheebow** [comment]
修正しました

**Comment by yuji** [comment]
build 95

**Comment by cmatsuo** [comment]
@yuji @cheebow 
未送信の記事／ウェブページから新規作成したものを削除した場合だけ、動作が違うのですが、これは意図的な仕様でしょうか？

**Comment by cheebow** [comment]
@cmatsuo 
未送信の記事から新規作成して、下書き保存したものを削除したときでしょうか？
僕の見落としかもしれません

**Comment by cheebow** [comment]
@cmatsuo 僕の見落としでした。修正しました

**Comment by yuji** [comment]
build 96

**Comment by cmatsuo** [comment]
verified fix!
