### ISSUE TITLE
L10N: 1.1 new feature and fix 2

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#234]
最後の x はなんだろうか？

![pic](https://cloud.githubusercontent.com/assets/546386/13481438/0f5a417c-e129-11e5-838a-01db077a5775.jpg)

**Comment by cmatsuo** [comment]
When you don't have permission to create entry.
* Do not have permission to create an entry.

![more](https://cloud.githubusercontent.com/assets/546386/13481749/95a54194-e12b-11e5-8ff8-c46274785842.jpg)

**Comment by cmatsuo** [comment]
When you don't have permission for upload image.
* Do not have permission to upload.

![up](https://cloud.githubusercontent.com/assets/546386/13481800/f6598464-e12b-11e5-8876-a92aa58f6c65.jpg)

**Comment by cmatsuo** [comment]
When user doesn't have permission for the website.
* Do not have permission to retrieve the requested fields.

![donothave](https://cloud.githubusercontent.com/assets/546386/13448178/39b355b4-e064-11e5-9f1c-02c4e80b1362.jpg)

**Comment by yuji** [comment]
x はゴミだった・・。
Do not have permission to xxxxx は Data API 側の出しているエラーメッセージのままで、のままで、ローカライズされていないからだと思う。（DefaultLanguage でローカライズとかできるのかな）

**Comment by yuji** [comment]
@cmatsuo ゴミ掃除は build 97

**Comment by cmatsuo** [comment]
@yuji ごみ掃除確認完了。

**Comment by cmatsuo** [comment]
User has no edit_asset permission 
* Do not have permission to delete an asset.

![asset](https://cloud.githubusercontent.com/assets/546386/13520210/bc66edb8-e221-11e5-95c4-426180d4bd81.jpg)

**Comment by cmatsuo** [comment]
「ページを送信しています…」→「ウェブページを送信しています…」かな

![webpage](https://cloud.githubusercontent.com/assets/546386/13595943/84d1cd9e-e552-11e5-85a7-9aa42f014170.jpg)

**Comment by yuji** [comment]
@cmatsuo ウェブページ修正

**Comment by cmatsuo** [comment]
ウェブページ修正確認

**Comment by yuji** [comment]
Permission 系のメッセージは API 側。

**Comment by cmatsuo** [comment]
アプリ側のものはL10N確認済み。API側のものは、 #244 に移動。
