### ISSUE TITLE
Unable to set time for customfields

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#235]
Steps:
1. Create "Date and Time", and "Time" Custom Fields for Entry (and Page) on CMS.
2. Go to Create New Entry on app.
3. Set date and time to the custom fields, send to MT.
4. Check Edit Entry which you created at step 4.

Expected: Find the values what you set for the CFs.
Observed: The fields for time are all "00:00:00".

**Comment by cheebow** [comment]
@yuji 送り方違いますか？

```
        {
        basename = datetime;
        value = 20160303114243;
    },

```

**Comment by yuji** [comment]
@cheebow まさに6.2.4で修正された部分で

Date&Time > 2015-12-18T17:10:00+09:00
Date > 2015-12-18
Time > 17:10:00+09:00

になっておりまして。API Version 3.1 以降は上記のように。それ以前（getVersionできてないもの含め
というか、今はそれしか無いですが）は、以前のような20160303114243で。

ということで。（すいません。下位互換性もたせられなかったのか・・ここは・・・）

**Comment by cheebow** [comment]
対応してみました！

**Comment by cheebow** [comment]
ちょっと修正します！
ビルドはお待ちを！

**Comment by cheebow** [comment]
修正できました！

**Comment by yuji** [comment]
@cmatsuo maybe fixed in build 99

**Comment by cmatsuo** [comment]
verified fix.
