### ISSUE TITLE
公開日、非公開日の日時指定がMTとアプリで異なる

### ISSUE THREAD

**Issue by cheebow** [movabletype/smartphone-app#236]
2016-03-03 11:01:53
でアプリ側で指定すると
2016-03-03 03:01:53
がMT側で表示されます。

**Comment by yuji** [comment]
@cheebow これ、AWSの開発環境ですかね？

**Comment by cheebow** [comment]
@yuji ですです

**Comment by yuji** [comment]
@cheebow Timezoneとかずれてるのか・・・サーバー見てみます！

**Comment by yuji** [comment]
9時間のズレではないな・・8時間ずれてるのか。なんでだ・・見てみよう・・。

**Comment by yuji** [comment]
$ date
2016年  3月  3日 木曜日 13:22:10 JST

ずれてなかった。

**Comment by yuji** [comment]
@cheebow DefaultLanguage が en_us のままだったので ja にしました。これでどうでしょ？（やったと思ったんだが・・・）

**Comment by cheebow** [comment]
@yuji @cmatsuo  だめみたいです。これAWSの問題なんですかね。他の環境ではどうでしょうか？

**Comment by yuji** [comment]
@cheebow わかった。firstBlog だと思うんですけど、タイムゾーンが UTCになってました。なので、ずれるの正解。My First Website (JST) のほうでは正しく表示されていました。
