### ISSUE TITLE
iOS8: Cannot display Licence page

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#240]
Go to > Settings > Licence.

![licens](https://cloud.githubusercontent.com/assets/546386/13559182/67664f68-e454-11e5-866f-7c193d7605ad.jpg)

**Comment by cheebow** [comment]
@cmatsuo こちらでは再現しないのですが、一度アプリを削除してから再インストールしても同じ現象が起きますか？
また、iOS8.xの小数点以下も教えてください。

**Comment by cmatsuo** [comment]
@cheebow 
一度削除しましたが、やはり発生します。
バージョン 8.3 (12F70)

**Comment by cheebow** [comment]
@cmatsuo 
やはりこちらでは再現できないので、思いついた別の実装を試させてください。
これでいかがでしょうか？

**Comment by yuji** [comment]
@cmatsuo build 104

**Comment by cmatsuo** [comment]
@cheebow @yuji 
状況変わりません。

FYI: 「ヘルプ」と「不具合を報告する」は問題なく表示されます。また、iOS9ではライセンスも問題なく表示できています。

**Comment by yuji** [comment]
@cheebow なんでなのかさっぱりわからないんですが・・。こちらのページも他と同様に サイト側で持つようにしちゃます？
GitHub に持たせてblobで参照でもいいかもですけど。

**Comment by cheebow** [comment]
iOS8.0のWKWebViewではローカルのファイルが読めない不具合(仕様？)があるみたいです。
なので、ローカルのファイルはHTML自体を読み込んでそれを表示するようにしてみました。

ちょっと試してみていただけますか？

**Comment by yuji** [comment]
@cmatsuo build 105

**Comment by cmatsuo** [comment]
verified fix.
