### ISSUE TITLE
On Unsent Entries/Pages, "Unpublish" doesn't appear on status setting screen.

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#241]
Steps:
1. Create an unpublished entry.
2. On app, go to Edit Entry of the unpublished entry, make sure the status is "Unpublish".
3. Save it to local.
4. Go to Unsent Entries > Edit Entry of the unpublished entry.
5. Tap status.

Expected: You can find "Unpublish" is checked.
Observed: "Unpublish" doesn't exist, and any status isn't checked.

![localstatus](https://cloud.githubusercontent.com/assets/546386/13562925/9e8a236c-e480-11e5-8775-7bce53199003.jpg)

**Comment by cheebow** [comment]
ストレージ保存時に非公開かどうかの情報を保存忘れしていました。
こちら修正します。

**Comment by cheebow** [comment]
修正しました

**Comment by yuji** [comment]
@cmatsuo build 106

**Comment by cmatsuo** [comment]
verified fix.
