### ISSUE TITLE
カスタムフィールド：複数行CFに改行を含めた文字列を保存した場合

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#95]
Steps:
1. アプリから、複数行のカスタムフィールドに、以下のように入力して、保存。MTに送信。
```
aaa
aaa
aaa
```
2.  MTで、送信した記事／ウェブページの編集画面を開き、複数行カスタムフィールドの入力内容を確認

Expected: 
```
aaa
aaa
aaa
```

Observed: 
```
aaa
<div>aaa</div>
<div>aaa</div>
```

**Comment by yuji** [comment]
By Design now...
